# Data Wrangling

# Part 1:  Preparations

## 1.1 import os and modules

In [1]:
import os
from urllib.request import urlopen
from json import loads
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.axis import Axis
from matplotlib.pyplot import figure
import matplotlib.colors as clrs
import datetime as dt
from matplotlib.dates import (DateFormatter, MinuteLocator, AutoDateLocator, AutoDateFormatter, datestr2num)
from pywaffle import Waffle

## 1.2 read in dataset(s)

In [2]:
bans = pd.read_excel (r'C:\Users\crathgeb-pc\Downloads\School_Book_Bans.xlsx', sheet_name='Sorted by State & District')
print(bans.head())

      State                        District Origin of Challenge  \
0    Alaska       Anchorage School District       Administrator
1  Arkansas  Siloam Springs School District    Formal Challenge
2   Florida   Brevard County Public Schools       Administrator
3   Florida   Brevard County Public Schools       Administrator
4   Florida   Brevard County Public Schools       Administrator

  Date of Challenge/Removal                           Type of Ban  \
0       2021-10-01 00:00:00  Banned from Libraries and Classrooms
1       2022-01-06 00:00:00  Banned from Libraries and Classrooms
2       2022-03-01 00:00:00          Banned Pending Investigation
3       2022-03-01 00:00:00          Banned Pending Investigation
4       2022-03-01 00:00:00          Banned Pending Investigation

             Author                                        Title  \
0      Kobabe, Maia                       Gender Queer: A Memoir
1     Kuklin, Susan  Beyond Magenta: Transgender Teens Speak Out
2    Andrews, Jesse                                   The Haters
3  Arnold, Elana K.                                       Damsel
4  Arnold, Elana K.                                    Infandous

  Secondary Author(s) Illustrator(s) Translator(s)
0                 NaN            NaN           NaN
1                 NaN            NaN           NaN
2                 NaN            NaN           NaN
3                 NaN            NaN           NaN
4                 NaN            NaN           NaN

In [3]:
url8 = "https://educationdata.urban.org/api/v1/school-districts/edfacts/assessments/2014/grade-8/"
response = urlopen(url8)
data8 = loads(response.read())

In [4]:
scores_gr_8 = pd.json_normalize(data8, record_path=['results'])
print(scores_gr_8.head())

     leaid  leaid_num  year          lea_name  fips  grade_edfacts  race  sex  \
0  0100005     100005  2014  Albertville City     1              8    99   99
1  0100006     100006  2014   Marshall County     1              8    99   99
2  0100007     100007  2014       Hoover City     1              8    99   99
3  0100008     100008  2014      Madison City     1              8    99   99
4  0100011     100011  2014        Leeds City     1              8    99   99

   lep  homeless  ...  military_connected  econ_disadvantaged  \
0   99        99  ...                  99                  99
1   99        99  ...                  99                  99
2   99        99  ...                  99                  99
3   99        99  ...                  99                  99
4   99        99  ...                  99                  99

   read_test_num_valid  read_test_pct_prof_low  read_test_pct_prof_high  \
0                334.0                    36.0                     36.0
1                393.0                    42.0                     42.0
2               1138.0                    67.0                     67.0
3                778.0                    67.0                     67.0
4                118.0                    50.0                     54.0

   read_test_pct_prof_midpt  math_test_num_valid  math_test_pct_prof_low  \
0                      36.0                339.0                    19.0
1                      42.0                393.0                    25.0
2                      67.0               1140.0                    61.0
3                      67.0                778.0                    59.0
4                      52.0                118.0                    30.0

   math_test_pct_prof_high  math_test_pct_prof_midpt
0                     19.0                      19.0
1                     25.0                      25.0
2                     61.0                      61.0
3                     59.0                      59.0
4                     34.0                      32.0

[5 rows x 23 columns]

In [5]:
scores_gr_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   leaid                     10000 non-null  object
 1   leaid_num                 10000 non-null  int64
 2   year                      10000 non-null  int64
 3   lea_name                  10000 non-null  object
 4   fips                      10000 non-null  int64
 5   grade_edfacts             10000 non-null  int64
 6   race                      10000 non-null  int64
 7   sex                       10000 non-null  int64
 8   lep                       10000 non-null  int64
 9   homeless                  10000 non-null  int64
 10  migrant                   10000 non-null  int64
 11  disability                10000 non-null  int64
 12  foster_care               10000 non-null  int64
 13  military_connected        10000 non-null  int64
 14  econ_disadvantaged        10000 non-null  int64
 15  read_test_num_valid       9982 non-null   float64
 16  read_test_pct_prof_low    9982 non-null   float64
 17  read_test_pct_prof_high   9982 non-null   float64
 18  read_test_pct_prof_midpt  9982 non-null   float64
 19  math_test_num_valid       9982 non-null   float64
 20  math_test_pct_prof_low    9982 non-null   float64
 21  math_test_pct_prof_high   9982 non-null   float64
 22  math_test_pct_prof_midpt  9982 non-null   float64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.8+ MB

In [6]:
scores_gr_8.describe()

,leaid_num,year,fips,grade_edfacts,race,sex,lep,homeless,migrant,disability,...,military_connected,econ_disadvantaged,read_test_num_valid,read_test_pct_prof_low,read_test_pct_prof_high,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_low,math_test_pct_prof_high,math_test_pct_prof_midpt
count,1.000000e+04,10000.0,10000.000000,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000
mean,2.277484e+06,2014.0,22.656100,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,243.665298,41.737528,51.484272,46.610900,239.831096,32.474755,42.406632,37.440693
std,1.123721e+06,0.0,11.237707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,827.059403,24.782752,25.122055,24.032147,828.476824,24.600137,24.879005,23.807711
min,1.000050e+05,2014.0,1.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,0.000000,-3.000000,-3.000000,-3.000000,0.000000,-3.000000,-3.000000,-3.000000
25%,1.601822e+06,2014.0,16.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,30.000000,24.000000,35.000000,28.000000,29.000000,11.000000,23.000000,22.000000
50%,2.511295e+06,2014.0,25.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,77.000000,41.000000,49.000000,47.000000,74.000000,30.000000,39.000000,33.000000
75%,3.302618e+06,2014.0,33.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,198.000000,60.000000,69.000000,67.000000,194.000000,50.000000,59.000000,54.500000
max,3.904957e+06,2014.0,39.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,36269.000000,99.000000,100.000000,99.500000,36204.000000,98.000000,100.000000,98.000000

In [7]:
url4 = "https://educationdata.urban.org/api/v1/school-districts/edfacts/assessments/2014/grade-4/"
response = urlopen(url4)
data4 = loads(response.read())

In [8]:
scores_gr_4 = pd.json_normalize(data4, record_path=['results'])
print(scores_gr_8.head())

     leaid  leaid_num  year          lea_name  fips  grade_edfacts  race  sex  \
0  0100005     100005  2014  Albertville City     1              8    99   99
1  0100006     100006  2014   Marshall County     1              8    99   99
2  0100007     100007  2014       Hoover City     1              8    99   99
3  0100008     100008  2014      Madison City     1              8    99   99
4  0100011     100011  2014        Leeds City     1              8    99   99

   lep  homeless  ...  military_connected  econ_disadvantaged  \
0   99        99  ...                  99                  99
1   99        99  ...                  99                  99
2   99        99  ...                  99                  99
3   99        99  ...                  99                  99
4   99        99  ...                  99                  99

   read_test_num_valid  read_test_pct_prof_low  read_test_pct_prof_high  \
0                334.0                    36.0                     36.0
1                393.0                    42.0                     42.0
2               1138.0                    67.0                     67.0
3                778.0                    67.0                     67.0
4                118.0                    50.0                     54.0

   read_test_pct_prof_midpt  math_test_num_valid  math_test_pct_prof_low  \
0                      36.0                339.0                    19.0
1                      42.0                393.0                    25.0
2                      67.0               1140.0                    61.0
3                      67.0                778.0                    59.0
4                      52.0                118.0                    30.0

   math_test_pct_prof_high  math_test_pct_prof_midpt
0                     19.0                      19.0
1                     25.0                      25.0
2                     61.0                      61.0
3                     59.0                      59.0
4                     34.0                      32.0

[5 rows x 23 columns]

In [9]:
scores_gr_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   leaid                     10000 non-null  object
 1   leaid_num                 10000 non-null  int64
 2   year                      10000 non-null  int64
 3   lea_name                  10000 non-null  object
 4   fips                      10000 non-null  int64
 5   grade_edfacts             10000 non-null  int64
 6   race                      10000 non-null  int64
 7   sex                       10000 non-null  int64
 8   lep                       10000 non-null  int64
 9   homeless                  10000 non-null  int64
 10  migrant                   10000 non-null  int64
 11  disability                10000 non-null  int64
 12  foster_care               10000 non-null  int64
 13  military_connected        10000 non-null  int64
 14  econ_disadvantaged        10000 non-null  int64
 15  read_test_num_valid       9988 non-null   float64
 16  read_test_pct_prof_low    9988 non-null   float64
 17  read_test_pct_prof_high   9988 non-null   float64
 18  read_test_pct_prof_midpt  9988 non-null   float64
 19  math_test_num_valid       9994 non-null   float64
 20  math_test_pct_prof_low    9994 non-null   float64
 21  math_test_pct_prof_high   9994 non-null   float64
 22  math_test_pct_prof_midpt  9994 non-null   float64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.8+ MB

In [10]:
scores_gr_4.describe()

,leaid_num,year,fips,grade_edfacts,race,sex,lep,homeless,migrant,disability,...,military_connected,econ_disadvantaged,read_test_num_valid,read_test_pct_prof_low,read_test_pct_prof_high,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_low,math_test_pct_prof_high,math_test_pct_prof_midpt
count,1.000000e+04,10000.0,10000.000000,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,9988.000000,9988.000000,9988.000000,9988.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,2.244830e+06,2014.0,22.329400,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,243.455447,40.625551,50.751802,45.688676,244.060536,36.910046,47.062237,41.986142
std,1.107791e+06,0.0,11.076306,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,877.255930,24.162648,24.933001,23.585568,882.157067,25.060535,25.481857,24.333023
min,1.000050e+05,2014.0,1.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,0.000000,-3.000000,-3.000000,-3.000000,0.000000,-3.000000,-3.000000,-3.000000
25%,1.600262e+06,2014.0,16.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,28.000000,21.000000,34.000000,27.000000,28.000000,20.000000,29.000000,24.500000
50%,2.507985e+06,2014.0,25.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,72.000000,40.000000,49.000000,47.000000,72.000000,40.000000,49.000000,42.000000
75%,3.172608e+06,2014.0,31.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,189.000000,60.000000,69.000000,65.000000,189.000000,55.000000,64.000000,62.000000
max,3.904576e+06,2014.0,39.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,42520.000000,97.000000,100.000000,97.500000,42699.000000,95.000000,100.000000,97.500000

# Part 2:  Basic summary info for each dataset

## 2.1 Bans Dataset

In [11]:
for col in bans.columns:
    print(col)

State
District
Origin of Challenge
Date of Challenge/Removal
Type of Ban
Author
Title
Secondary Author(s)
Illustrator(s)
Translator(s)

In [12]:
bans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586 entries, 0 to 1585
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   State                      1586 non-null   object
 1   District                   1586 non-null   object
 2   Origin of Challenge        1586 non-null   object
 3   Date of Challenge/Removal  1586 non-null   object
 4   Type of Ban                1586 non-null   object
 5   Author                     1586 non-null   object
 6   Title                      1586 non-null   object
 7   Secondary Author(s)        98 non-null     object
 8   Illustrator(s)             364 non-null    object
 9   Translator(s)              10 non-null     object
dtypes: object(10)
memory usage: 124.0+ KB

In [13]:
bans.describe()

,State,District,Origin of Challenge,Date of Challenge/Removal,Type of Ban,Author,Title,Secondary Author(s),Illustrator(s),Translator(s)
count,1586,1586,1586,1586,1586,1586,1586,98,364,10
unique,26,86,2,15,4,797,1145,61,192,9
top,Texas,Central York,Administrator,2021-09-01 00:00:00,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,"Cast, Kristin","Aly, Hatem","Mlawer, Teresa"
freq,713,441,1517,456,731,30,30,12,17,2

## 2.2 Grade 8 scores dataset

In [14]:
for col in scores_gr_8.columns:
    print(col)

leaid
leaid_num
year
lea_name
fips
grade_edfacts
race
sex
lep
homeless
migrant
disability
foster_care
military_connected
econ_disadvantaged
read_test_num_valid
read_test_pct_prof_low
read_test_pct_prof_high
read_test_pct_prof_midpt
math_test_num_valid
math_test_pct_prof_low
math_test_pct_prof_high
math_test_pct_prof_midpt

In [15]:
scores_gr_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   leaid                     10000 non-null  object
 1   leaid_num                 10000 non-null  int64
 2   year                      10000 non-null  int64
 3   lea_name                  10000 non-null  object
 4   fips                      10000 non-null  int64
 5   grade_edfacts             10000 non-null  int64
 6   race                      10000 non-null  int64
 7   sex                       10000 non-null  int64
 8   lep                       10000 non-null  int64
 9   homeless                  10000 non-null  int64
 10  migrant                   10000 non-null  int64
 11  disability                10000 non-null  int64
 12  foster_care               10000 non-null  int64
 13  military_connected        10000 non-null  int64
 14  econ_disadvantaged        10000 non-null  int64
 15  read_test_num_valid       9982 non-null   float64
 16  read_test_pct_prof_low    9982 non-null   float64
 17  read_test_pct_prof_high   9982 non-null   float64
 18  read_test_pct_prof_midpt  9982 non-null   float64
 19  math_test_num_valid       9982 non-null   float64
 20  math_test_pct_prof_low    9982 non-null   float64
 21  math_test_pct_prof_high   9982 non-null   float64
 22  math_test_pct_prof_midpt  9982 non-null   float64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.8+ MB

In [16]:
scores_gr_8.describe()

,leaid_num,year,fips,grade_edfacts,race,sex,lep,homeless,migrant,disability,...,military_connected,econ_disadvantaged,read_test_num_valid,read_test_pct_prof_low,read_test_pct_prof_high,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_low,math_test_pct_prof_high,math_test_pct_prof_midpt
count,1.000000e+04,10000.0,10000.000000,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000,9982.000000
mean,2.277484e+06,2014.0,22.656100,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,243.665298,41.737528,51.484272,46.610900,239.831096,32.474755,42.406632,37.440693
std,1.123721e+06,0.0,11.237707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,827.059403,24.782752,25.122055,24.032147,828.476824,24.600137,24.879005,23.807711
min,1.000050e+05,2014.0,1.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,0.000000,-3.000000,-3.000000,-3.000000,0.000000,-3.000000,-3.000000,-3.000000
25%,1.601822e+06,2014.0,16.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,30.000000,24.000000,35.000000,28.000000,29.000000,11.000000,23.000000,22.000000
50%,2.511295e+06,2014.0,25.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,77.000000,41.000000,49.000000,47.000000,74.000000,30.000000,39.000000,33.000000
75%,3.302618e+06,2014.0,33.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,198.000000,60.000000,69.000000,67.000000,194.000000,50.000000,59.000000,54.500000
max,3.904957e+06,2014.0,39.000000,8.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,36269.000000,99.000000,100.000000,99.500000,36204.000000,98.000000,100.000000,98.000000

## 2.3 Grade 4 scores dataset

In [17]:
for col in scores_gr_8.columns:
    print(col)

leaid
leaid_num
year
lea_name
fips
grade_edfacts
race
sex
lep
homeless
migrant
disability
foster_care
military_connected
econ_disadvantaged
read_test_num_valid
read_test_pct_prof_low
read_test_pct_prof_high
read_test_pct_prof_midpt
math_test_num_valid
math_test_pct_prof_low
math_test_pct_prof_high
math_test_pct_prof_midpt

In [18]:
scores_gr_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   leaid                     10000 non-null  object
 1   leaid_num                 10000 non-null  int64
 2   year                      10000 non-null  int64
 3   lea_name                  10000 non-null  object
 4   fips                      10000 non-null  int64
 5   grade_edfacts             10000 non-null  int64
 6   race                      10000 non-null  int64
 7   sex                       10000 non-null  int64
 8   lep                       10000 non-null  int64
 9   homeless                  10000 non-null  int64
 10  migrant                   10000 non-null  int64
 11  disability                10000 non-null  int64
 12  foster_care               10000 non-null  int64
 13  military_connected        10000 non-null  int64
 14  econ_disadvantaged        10000 non-null  int64
 15  read_test_num_valid       9988 non-null   float64
 16  read_test_pct_prof_low    9988 non-null   float64
 17  read_test_pct_prof_high   9988 non-null   float64
 18  read_test_pct_prof_midpt  9988 non-null   float64
 19  math_test_num_valid       9994 non-null   float64
 20  math_test_pct_prof_low    9994 non-null   float64
 21  math_test_pct_prof_high   9994 non-null   float64
 22  math_test_pct_prof_midpt  9994 non-null   float64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.8+ MB

In [19]:
scores_gr_4.describe()

,leaid_num,year,fips,grade_edfacts,race,sex,lep,homeless,migrant,disability,...,military_connected,econ_disadvantaged,read_test_num_valid,read_test_pct_prof_low,read_test_pct_prof_high,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_low,math_test_pct_prof_high,math_test_pct_prof_midpt
count,1.000000e+04,10000.0,10000.000000,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,9988.000000,9988.000000,9988.000000,9988.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,2.244830e+06,2014.0,22.329400,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,243.455447,40.625551,50.751802,45.688676,244.060536,36.910046,47.062237,41.986142
std,1.107791e+06,0.0,11.076306,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,877.255930,24.162648,24.933001,23.585568,882.157067,25.060535,25.481857,24.333023
min,1.000050e+05,2014.0,1.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,0.000000,-3.000000,-3.000000,-3.000000,0.000000,-3.000000,-3.000000,-3.000000
25%,1.600262e+06,2014.0,16.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,28.000000,21.000000,34.000000,27.000000,28.000000,20.000000,29.000000,24.500000
50%,2.507985e+06,2014.0,25.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,72.000000,40.000000,49.000000,47.000000,72.000000,40.000000,49.000000,42.000000
75%,3.172608e+06,2014.0,31.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,189.000000,60.000000,69.000000,65.000000,189.000000,55.000000,64.000000,62.000000
max,3.904576e+06,2014.0,39.000000,4.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,42520.000000,97.000000,100.000000,97.500000,42699.000000,95.000000,100.000000,97.500000

# Part 3:  Clean datasets

## 3.1 Clean banned book dataset

### 3.1.1 Create column for how frequently each title is banned

In [20]:
bans['Title'].value_counts().head(220)

Gender Queer: A Memoir                           30
All Boys Aren't Blue                             21
Lawn Boy                                         16
Out of Darkness                                  16
The Bluest Eye                                   12
                                                 ..
LGBTQ Families: The Ultimate Teen Guide           1
Red Hood                                          1
Y: The Last Man                                   1
The Accidental Adventures of India McAllister     1
How It All Blew Up                                1
Name: Title, Length: 220, dtype: int64

In [21]:
df2 = pd.DataFrame().assign(Title=bans['Title'])
print(df2)

                                                  Title
0                                Gender Queer: A Memoir
1           Beyond Magenta: Transgender Teens Speak Out
2                                            The Haters
3                                                Damsel
4                                             Infandous
...                                                 ...
1581          Queer: The Ultimate LGBTQ Guide for Teens
1582                                   This Book Is Gay
1583                                      The Baby Tree
1584                    Protest Movements: Then and Now
1585  Pride: The Story of Harvey Milk and the Rainbo...

[1586 rows x 1 columns]

In [22]:
df2['frequency'] = df2['Title'].map(df2['Title'].value_counts())
print(df2.head(5))

                                         Title  frequency
0                       Gender Queer: A Memoir         30
1  Beyond Magenta: Transgender Teens Speak Out         11
2                                   The Haters          2
3                                       Damsel          1
4                                    Infandous          2

In [23]:
bans['Frequency'] = df2['frequency']
print(bans.head())

      State                        District Origin of Challenge  \
0    Alaska       Anchorage School District       Administrator
1  Arkansas  Siloam Springs School District    Formal Challenge
2   Florida   Brevard County Public Schools       Administrator
3   Florida   Brevard County Public Schools       Administrator
4   Florida   Brevard County Public Schools       Administrator

  Date of Challenge/Removal                           Type of Ban  \
0       2021-10-01 00:00:00  Banned from Libraries and Classrooms
1       2022-01-06 00:00:00  Banned from Libraries and Classrooms
2       2022-03-01 00:00:00          Banned Pending Investigation
3       2022-03-01 00:00:00          Banned Pending Investigation
4       2022-03-01 00:00:00          Banned Pending Investigation

             Author                                        Title  \
0      Kobabe, Maia                       Gender Queer: A Memoir
1     Kuklin, Susan  Beyond Magenta: Transgender Teens Speak Out
2    Andrews, Jesse                                   The Haters
3  Arnold, Elana K.                                       Damsel
4  Arnold, Elana K.                                    Infandous

  Secondary Author(s) Illustrator(s) Translator(s)  Frequency
0                 NaN            NaN           NaN         30
1                 NaN            NaN           NaN         11
2                 NaN            NaN           NaN          2
3                 NaN            NaN           NaN          1
4                 NaN            NaN           NaN          2

In [24]:
bans.sort_values(by=["Frequency"], inplace=True, ascending=False)
print(bans.head())

             State                          District Origin of Challenge  \
0           Alaska         Anchorage School District       Administrator
817   Pennsylvania                       Wissahickon       Administrator
1545         Texas                 Spring Branch ISD       Administrator
1535         Texas                       Prosper ISD       Administrator
303       New York  Yorktown Central School District    Formal Challenge

     Date of Challenge/Removal                           Type of Ban  \
0          2021-10-01 00:00:00  Banned from Libraries and Classrooms
817        2021-10-01 00:00:00          Banned Pending Investigation
1545       2021-11-01 00:00:00  Banned from Libraries and Classrooms
1535                 Fall 2021  Banned from Libraries and Classrooms
303        2022-01-01 00:00:00          Banned Pending Investigation

            Author                   Title Secondary Author(s) Illustrator(s)  \
0     Kobabe, Maia  Gender Queer: A Memoir                 NaN            NaN
817   Kobabe, Maia  Gender Queer: A Memoir                 NaN            NaN
1545  Kobabe, Maia  Gender Queer: A Memoir                 NaN            NaN
1535  Kobabe, Maia  Gender Queer: A Memoir                 NaN            NaN
303   Kobabe, Maia  Gender Queer: A Memoir                 NaN            NaN

     Translator(s)  Frequency
0              NaN         30
817            NaN         30
1545           NaN         30
1535           NaN         30
303            NaN         30

### 3.1.2 Create a new (simplified) dataset containing only the most controversial books (i.e. those books banned three or more times).

In [25]:
Most_Controversial = bans[['Title', 'Author', 'Date of Challenge/Removal', 'Frequency']].copy()
print(Most_Controversial.head())

                       Title        Author Date of Challenge/Removal  \
0     Gender Queer: A Memoir  Kobabe, Maia       2021-10-01 00:00:00
817   Gender Queer: A Memoir  Kobabe, Maia       2021-10-01 00:00:00
1545  Gender Queer: A Memoir  Kobabe, Maia       2021-11-01 00:00:00
1535  Gender Queer: A Memoir  Kobabe, Maia                 Fall 2021
303   Gender Queer: A Memoir  Kobabe, Maia       2022-01-01 00:00:00

      Frequency
0            30
817          30
1545         30
1535         30
303          30

In [26]:
Most_Controversial = Most_Controversial[Most_Controversial.Frequency >= 3]

### 3.1.3 Create a new dataset focused on trends in book banning by state.

In [27]:
State_Info = bans[['State', 'District', 'Date of Challenge/Removal']].copy()

In [28]:
State_Info['State_Frequency'] = State_Info['State'].map(bans['State'].value_counts())

In [29]:
State_Info['District_Frequency'] = State_Info['District'].map(bans['District'].value_counts())

In [30]:
State_Info.sort_values(by=['State_Frequency', 'District_Frequency'], inplace=True, ascending=(False, False))
print(State_Info.head())

      State    District Date of Challenge/Removal  State_Frequency  \
1277  Texas  North East       2021-12-01 00:00:00              713
1190  Texas  North East       2021-12-01 00:00:00              713
1306  Texas  North East       2021-12-01 00:00:00              713
1097  Texas  North East       2021-12-01 00:00:00              713
1404  Texas  North East       2021-12-01 00:00:00              713

      District_Frequency
1277                 435
1190                 435
1306                 435
1097                 435
1404                 435

### 3.1.4 Examine information about school districts (from the most relevant states--those with the most bans)

In [31]:
tx_districts = bans.loc[bans['State'] == 'Texas']
pn_districts = bans.loc[bans['State'] == 'Pennsylvania']
fl_districts = bans.loc[bans['State'] == 'Florida']
ok_districts = bans.loc[bans['State'] == 'Oklahoma']
ks_districts = bans.loc[bans['State'] == 'Kansas']
in_districts = bans.loc[bans['State'] == 'Indiana']
va_districts = bans.loc[bans['State'] == 'Virginia']
tn_districts = bans.loc[bans['State'] == 'Tennessee']
mo_districts = bans.loc[bans['State'] == 'Missouri']
ga_districts = bans.loc[bans['State'] == 'Georgia']
ny_districts = bans.loc[bans['State'] == 'New York']
ut_districts = bans.loc[bans['State'] == 'Utah']
nc_districts = bans.loc[bans['State'] == 'North Carolina']
ws_districts = bans.loc[bans['State'] == 'Wisconsin']
wa_districts = bans.loc[bans['State'] == 'Washington']
il_districts = bans.loc[bans['State'] == 'Illinois']
io_districts = bans.loc[bans['State'] == 'Iowa']
oh_districts = bans.loc[bans['State'] == 'Ohio']
nj_districts = bans.loc[bans['State'] == 'New Jersey']
mi_districts = bans.loc[bans['State'] == 'Michigan']

print(ga_districts)

       State                District Origin of Challenge  \
209  Georgia  Forsyth County Schools       Administrator
214  Georgia  Forsyth County Schools       Administrator
211  Georgia  Forsyth County Schools       Administrator
207  Georgia  Forsyth County Schools       Administrator
212  Georgia  Forsyth County Schools       Administrator
217  Georgia  Forsyth County Schools       Administrator
206  Georgia  Forsyth County Schools       Administrator
208  Georgia  Forsyth County Schools       Administrator
213  Georgia  Forsyth County Schools       Administrator
216  Georgia  Forsyth County Schools       Administrator
215  Georgia  Forsyth County Schools       Administrator
210  Georgia  Forsyth County Schools       Administrator
218  Georgia  Forsyth County Schools       Administrator

    Date of Challenge/Removal                           Type of Ban  \
209       2022-01-31 00:00:00  Banned from Libraries and Classrooms
214       2022-01-31 00:00:00  Banned from Libraries and Classrooms
211       2022-01-31 00:00:00  Banned from Libraries and Classrooms
207       2022-01-31 00:00:00  Banned from Libraries and Classrooms
212       2022-01-31 00:00:00  Banned from Libraries and Classrooms
217       2022-01-31 00:00:00                 Banned from Libraries
206       2022-01-31 00:00:00                 Banned from Libraries
208       2022-01-31 00:00:00                 Banned from Libraries
213       2022-01-31 00:00:00  Banned from Libraries and Classrooms
216       2022-01-31 00:00:00  Banned from Libraries and Classrooms
215       2022-01-31 00:00:00  Banned from Libraries and Classrooms
210       2022-01-31 00:00:00                 Banned from Libraries
218           prior to 1/2022  Banned from Libraries and Classrooms

                 Author                                            Title  \
209  Johnson, George M.                             All Boys Aren't Blue
214  Pérez, Ashley Hope                                  Out of Darkness
211      Morrison, Toni                                   The Bluest Eye
207      Andrews, Jesse                   Me and Earl and the Dying Girl
212     Myracle, Lauren                                         l8r, g8r
217      Tamaki, Mariko                                  This One Summer
206     Alexie, Sherman  The Absolutely True Diary of a Part-Time Indian
208    Atwood, Margaret                              The Handmaid's Tale
213     Myracle, Lauren                        The Infinite Moment of Us
216       Rivera, Gabby                            Juliet Takes a Breath
215       Picoult, Jodi                                 Nineteen Minutes
210     Levithan, David                                 Two Boys Kissing
218        Ukazu, Ngozi                  #Hockey (Check, Please! Series)

    Secondary Author(s)  Illustrator(s) Translator(s)  Frequency
209                 NaN             NaN           NaN         21
214                 NaN             NaN           NaN         16
211                 NaN             NaN           NaN         12
207                 NaN             NaN           NaN          9
212                 NaN             NaN           NaN          8
217                 NaN  Jillian Tamaki           NaN          7
206                 NaN   Forney, Ellen           NaN          6
208                 NaN             NaN           NaN          6
213                 NaN             NaN           NaN          4
216                 NaN             NaN           NaN          3
215                 NaN             NaN           NaN          3
210                 NaN             NaN           NaN          3
218                 NaN             NaN           NaN          2

In [32]:
district_list = [tx_districts, pn_districts, fl_districts, ok_districts, ks_districts, in_districts, va_districts, 
        tn_districts, mo_districts, ga_districts, ny_districts, ut_districts, nc_districts, ws_districts, 
        wa_districts, il_districts, io_districts, oh_districts, nj_districts, mi_districts]
district = pd.concat(district_list)
print(district)

           State                               District Origin of Challenge  \
1545       Texas                      Spring Branch ISD       Administrator
1535       Texas                            Prosper ISD       Administrator
1042       Texas                                 Keller    Formal Challenge
842        Texas                              Birdville    Formal Challenge
851        Texas  Canutillo Independent School District       Administrator
...          ...                                    ...                 ...
295   New Jersey         Sparta Township Public Schools       Administrator
294   New Jersey              Lower Township Elementary    Formal Challenge
296   New Jersey                              Westfield    Formal Challenge
277     Michigan         Novi Community School District    Formal Challenge
276     Michigan             Hudsonville Public Schools    Formal Challenge

     Date of Challenge/Removal                           Type of Ban  \
1545       2021-11-01 00:00:00  Banned from Libraries and Classrooms
1535                 Fall 2021  Banned from Libraries and Classrooms
1042       2021-11-01 00:00:00  Banned from Libraries and Classrooms
842                  Fall 2021          Banned Pending Investigation
851        2021-10-01 00:00:00  Banned from Libraries and Classrooms
...                        ...                                   ...
295        2021-09-01 00:00:00                Banned from Classrooms
294        2022-02-01 00:00:00          Banned Pending Investigation
296                  Fall 2021                 Banned from Libraries
277        2022-01-01 00:00:00                 Banned from Libraries
276        2022-01-01 00:00:00                Banned from Classrooms

                         Author                                      Title  \
1545               Kobabe, Maia                     Gender Queer: A Memoir
1535               Kobabe, Maia                     Gender Queer: A Memoir
1042               Kobabe, Maia                     Gender Queer: A Memoir
842                Kobabe, Maia                     Gender Queer: A Memoir
851                Kobabe, Maia                     Gender Queer: A Memoir
...                         ...                                        ...
295       Rhodes, Jewell Parker                                 Ghost Boys
294               Volponi, Paul                            Black and White
296              Madison, Megan  Our Skin: A First Conversation About Race
277            Evison, Jonathan                                   Lawn Boy
276   Adichie, Chimamanda Ngozi                       Half of a Yellow Sun

     Secondary Author(s) Illustrator(s) Translator(s)  Frequency
1545                 NaN            NaN           NaN         30
1535                 NaN            NaN           NaN         30
1042                 NaN            NaN           NaN         30
842                  NaN            NaN           NaN         30
851                  NaN            NaN           NaN         30
...                  ...            ...           ...        ...
295                  NaN            NaN           NaN          4
294                  NaN            NaN           NaN          1
296       Ralli, Jessica  Roxas, Isabel           NaN          1
277                  NaN            NaN           NaN         16
276                  NaN            NaN           NaN          1

[1580 rows x 11 columns]

In [33]:
district.drop(['Author', 'Title', 'Type of Ban', 'Secondary Author(s)', 'Illustrator(s)', 'Translator(s)', 'Origin of Challenge', 'Frequency'], axis=1, inplace=True)

One thing I notice in these results are that the column "Date of Challenge/Removal" is in different formats.  We should standardize this.

### 3.1.5 Edit date/datetime

In [34]:
bans['Date'] = pd.to_datetime(bans["Date of Challenge/Removal"], errors='coerce').dt.date

Those rows listed as "Fall 2012" now show "NaT."  Let's fix this.  (I chose Nov 7th to replace the value "Fall" as it is approximately the very middle of the fall season.)

In [35]:
bans['Date of Challenge/Removal'].replace({'Fall 2021': '2021-11-07 00:00:00'}, inplace = True)

In [36]:
bans['Date'].replace({np.nan: '2021-11-07'}, inplace = True)
print(bans)

             State                              District Origin of Challenge  \
0           Alaska             Anchorage School District       Administrator
817   Pennsylvania                           Wissahickon       Administrator
1545         Texas                     Spring Branch ISD       Administrator
1535         Texas                           Prosper ISD       Administrator
303       New York      Yorktown Central School District    Formal Challenge
...            ...                                   ...                 ...
958          Texas  Granbury Independent School District       Administrator
544   Pennsylvania                          Central York       Administrator
543   Pennsylvania                          Central York       Administrator
542   Pennsylvania                          Central York       Administrator
793   Pennsylvania                          Central York       Administrator

     Date of Challenge/Removal                           Type of Ban  \
0          2021-10-01 00:00:00  Banned from Libraries and Classrooms
817        2021-10-01 00:00:00          Banned Pending Investigation
1545       2021-11-01 00:00:00  Banned from Libraries and Classrooms
1535       2021-11-07 00:00:00  Banned from Libraries and Classrooms
303        2022-01-01 00:00:00          Banned Pending Investigation
...                        ...                                   ...
958        2022-01-01 00:00:00          Banned Pending Investigation
544        2021-09-01 00:00:00                Banned from Classrooms
543        2021-09-01 00:00:00                Banned from Classrooms
542        2021-09-01 00:00:00                Banned from Classrooms
793        2021-09-01 00:00:00                Banned from Classrooms

                         Author  \
0                  Kobabe, Maia
817                Kobabe, Maia
1545               Kobabe, Maia
1535               Kobabe, Maia
303                Kobabe, Maia
...                         ...
958   Johnson, Kathleen Jeffrie
544            Hubbard, Crystal
543                 Hort, Lenny
542          Hopkinson, Deborah
793       Worthington, Michelle

                                                  Title Secondary Author(s)  \
0                                Gender Queer: A Memoir                 NaN
817                              Gender Queer: A Memoir                 NaN
1545                             Gender Queer: A Memoir                 NaN
1535                             Gender Queer: A Memoir                 NaN
303                              Gender Queer: A Memoir                 NaN
...                                                 ...                 ...
958                                              Target                 NaN
544   Catching the Moon: The Story of a Young Girl's...                 NaN
543                          How Many Stars in the Sky?                 NaN
542   What Is the Women's Rights Movement? (What was...                 NaN
793                                Noah Chases the Wind                 NaN

         Illustrator(s) Translator(s)  Frequency        Date
0                   NaN           NaN         30  2021-10-01
817                 NaN           NaN         30  2021-10-01
1545                NaN           NaN         30  2021-11-01
1535                NaN           NaN         30  2021-11-07
303                 NaN           NaN         30  2022-01-01
...                 ...           ...        ...         ...
958                 NaN           NaN          1  2022-01-01
544      DuBurke, Randy           NaN          1  2021-09-01
543   Ransome, James E.           NaN          1  2021-09-01
542      Conley, Laurie           NaN          1  2021-09-01
793      Cowman, Joseph           NaN          1  2021-09-01

[1586 rows x 12 columns]

### 3.1.6 Keep only columns we may use for the project

In [37]:
bans.drop(['Secondary Author(s)', 'Illustrator(s)', 'Translator(s)', 'Date of Challenge/Removal'], axis = 1, inplace = True)
print(bans)

             State                              District Origin of Challenge  \
0           Alaska             Anchorage School District       Administrator
817   Pennsylvania                           Wissahickon       Administrator
1545         Texas                     Spring Branch ISD       Administrator
1535         Texas                           Prosper ISD       Administrator
303       New York      Yorktown Central School District    Formal Challenge
...            ...                                   ...                 ...
958          Texas  Granbury Independent School District       Administrator
544   Pennsylvania                          Central York       Administrator
543   Pennsylvania                          Central York       Administrator
542   Pennsylvania                          Central York       Administrator
793   Pennsylvania                          Central York       Administrator

                               Type of Ban                     Author  \
0     Banned from Libraries and Classrooms               Kobabe, Maia
817           Banned Pending Investigation               Kobabe, Maia
1545  Banned from Libraries and Classrooms               Kobabe, Maia
1535  Banned from Libraries and Classrooms               Kobabe, Maia
303           Banned Pending Investigation               Kobabe, Maia
...                                    ...                        ...
958           Banned Pending Investigation  Johnson, Kathleen Jeffrie
544                 Banned from Classrooms           Hubbard, Crystal
543                 Banned from Classrooms                Hort, Lenny
542                 Banned from Classrooms         Hopkinson, Deborah
793                 Banned from Classrooms      Worthington, Michelle

                                                  Title  Frequency        Date
0                                Gender Queer: A Memoir         30  2021-10-01
817                              Gender Queer: A Memoir         30  2021-10-01
1545                             Gender Queer: A Memoir         30  2021-11-01
1535                             Gender Queer: A Memoir         30  2021-11-07
303                              Gender Queer: A Memoir         30  2022-01-01
...                                                 ...        ...         ...
958                                              Target          1  2022-01-01
544   Catching the Moon: The Story of a Young Girl's...          1  2021-09-01
543                          How Many Stars in the Sky?          1  2021-09-01
542   What Is the Women's Rights Movement? (What was...          1  2021-09-01
793                                Noah Chases the Wind          1  2021-09-01

[1586 rows x 8 columns]

## 3.2  Merge scores datasets

In [38]:
scores_together = pd.merge(scores_gr_4, scores_gr_8, how='outer', on=['leaid', 'leaid_num', 'year', 'lea_name'])
print(scores_together.head())

     leaid  leaid_num  year          lea_name  fips_x  grade_edfacts_x  \
0  0100005     100005  2014  Albertville City     1.0              4.0
1  0100006     100006  2014   Marshall County     1.0              4.0
2  0100007     100007  2014       Hoover City     1.0              4.0
3  0100008     100008  2014      Madison City     1.0              4.0
4  0100011     100011  2014        Leeds City     1.0              4.0

   race_x  sex_x  lep_x  homeless_x  ...  military_connected_y  \
0    99.0   99.0   99.0        99.0  ...                  99.0
1    99.0   99.0   99.0        99.0  ...                  99.0
2    99.0   99.0   99.0        99.0  ...                  99.0
3    99.0   99.0   99.0        99.0  ...                  99.0
4    99.0   99.0   99.0        99.0  ...                  99.0

   econ_disadvantaged_y  read_test_num_valid_y  read_test_pct_prof_low_y  \
0                  99.0                  334.0                      36.0
1                  99.0                  393.0                      42.0
2                  99.0                 1138.0                      67.0
3                  99.0                  778.0                      67.0
4                  99.0                  118.0                      50.0

   read_test_pct_prof_high_y  read_test_pct_prof_midpt_y  \
0                       36.0                        36.0
1                       42.0                        42.0
2                       67.0                        67.0
3                       67.0                        67.0
4                       54.0                        52.0

   math_test_num_valid_y  math_test_pct_prof_low_y  math_test_pct_prof_high_y  \
0                  339.0                      19.0                       19.0
1                  393.0                      25.0                       25.0
2                 1140.0                      61.0                       61.0
3                  778.0                      59.0                       59.0
4                  118.0                      30.0                       34.0

   math_test_pct_prof_midpt_y
0                        19.0
1                        25.0
2                        61.0
3                        59.0
4                        32.0

[5 rows x 42 columns]

## 3.3 Clean merged scores dataset

### 3.3.1 Drop columns that we will not use for this project

In [39]:
scores = scores_together.drop(['leaid_num', 'grade_edfacts_x', 'grade_edfacts_y', 'fips_x', 'race_x', 'sex_x', 'lep_x', 'migrant_x', 'disability_x', 'foster_care_x', 'military_connected_x', 'econ_disadvantaged_x', 'homeless_x', 'sex_y', 'lep_y', 'homeless_y', 'migrant_y', 'disability_y', 'foster_care_y', 'military_connected_y', 'econ_disadvantaged_y', 'math_test_num_valid_y', 'math_test_pct_prof_low_y', 'math_test_pct_prof_high_y', 'math_test_pct_prof_midpt_y', 'fips_y', 'race_y'], axis=1)
print(scores.head(50))

      leaid  year          lea_name  read_test_num_valid_x  \
0   0100005  2014  Albertville City                  389.0
1   0100006  2014   Marshall County                  440.0
2   0100007  2014       Hoover City                 1011.0
3   0100008  2014      Madison City                  734.0
4   0100011  2014        Leeds City                  145.0
5   0100012  2014         Boaz City                  194.0
6   0100013  2014   Trussville City                  332.0
7   0100030  2014    Alexander City                  215.0
8   0100060  2014    Andalusia City                  121.0
9   0100090  2014     Anniston City                  156.0
10  0100100  2014         Arab City                  189.0
11  0100120  2014       Athens City                  254.0
12  0100180  2014      Attalla City                   80.0
13  0100185  2014     Saraland City                  208.0
14  0100188  2014    Chickasaw City                   63.0
15  0100189  2014      Satsuma City                   99.0
16  0100190  2014    Alabaster City                  466.0
17  0100194  2014       Pelham City                  256.0
18  0100210  2014       Auburn City                  643.0
19  0100240  2014    Autauga County                  728.0
20  0100270  2014    Baldwin County                 2341.0
21  0100300  2014    Barbour County                   66.0
22  0100330  2014     Bessemer City                  304.0
23  0100360  2014       Bibb County                  233.0
24  0100390  2014   Birmingham City                 1877.0
25  0100420  2014     Blount County                  614.0
26  0100450  2014      Brewton City                   89.0
27  0100480  2014    Bullock County                  104.0
28  0100510  2014     Butler County                  222.0
29  0100540  2014    Calhoun County                  671.0
30  0100600  2014   Chambers County                  275.0
31  0100630  2014   Cherokee County                  292.0
32  0100660  2014    Chilton County                  592.0
33  0100690  2014    Choctaw County                  112.0
34  0100720  2014     Clarke County                  189.0
35  0100750  2014       Clay County                  121.0
36  0100780  2014   Cleburne County                  213.0
37  0100810  2014     Coffee County                  155.0
38  0100840  2014    Colbert County                  185.0
39  0100870  2014    Conecuh County                   88.0
40  0100900  2014      Coosa County                   72.0
41  0100930  2014  Covington County                  257.0
42  0100960  2014   Crenshaw County                  145.0
43  0100990  2014      Cullman City                  246.0
44  0101020  2014    Cullman County                  711.0
45  0101050  2014       Dale County                  210.0
46  0101080  2014    Daleville City                   64.0
47  0101110  2014     Dallas County                  197.0
48  0101140  2014     Dekalb County                  660.0
49  0101170  2014      Decatur City                  642.0

    read_test_pct_prof_low_x  read_test_pct_prof_high_x  \
0                       31.0                       31.0
1                       29.0                       29.0
2                       56.0                       56.0
3                       70.0                       70.0
4                       20.0                       24.0
5                       35.0                       39.0
6                       58.0                       58.0
7                       30.0                       34.0
8                       20.0                       24.0
9                       15.0                       19.0
10                      55.0                       59.0
11                      50.0                       54.0
12                      45.0                       49.0
13                      50.0                       54.0
14                      15.0                       19.0
15                      40.0                       44.0
16                      33.0                       33.0
17                      50.0                       54.0
18                      56.0                       56.0
19                      36.0                       36.0
20                      36.0                       36.0
21                      10.0                       14.0
22                      12.0                       12.0
23                      30.0                       34.0
24                      15.0                       15.0
25                      42.0                       42.0
26                      50.0                       54.0
27                      15.0                       19.0
28                      20.0                       24.0
29                      36.0                       36.0
30                      30.0                       34.0
31                      45.0                       49.0
32                      28.0                       28.0
33                      20.0                       24.0
34                      20.0                       24.0
35                      35.0                       39.0
36                      40.0                       44.0
37                      30.0                       34.0
38                      20.0                       24.0
39                      20.0                       24.0
40                      15.0                       19.0
41                      35.0                       39.0
42                      20.0                       24.0
43                      50.0                       54.0
44                      33.0                       33.0
45                      40.0                       44.0
46                      25.0                       29.0
47                      15.0                       19.0
48                      26.0                       26.0
49                      28.0                       28.0

    read_test_pct_prof_midpt_x  math_test_num_valid_x  \
0                         31.0                  392.0
1                         29.0                  440.0
2                         56.0                 1011.0
3                         70.0                  736.0
4                         22.0                  146.0
5                         37.0                  197.0
6                         58.0                  333.0
7                         32.0                  217.0
8                         22.0                  121.0
9                         17.0                  156.0
10                        57.0                  189.0
11                        52.0                  254.0
12                        47.0                   80.0
13                        52.0                  209.0
14                        17.0                   63.0
15                        42.0                   99.0
16                        33.0                  465.0
17                        52.0                  257.0
18                        56.0                  648.0
19                        36.0                  726.0
20                        36.0                 2339.0
21                        12.0                   66.0
22                        12.0                  305.0
23                        32.0                  233.0
24                        15.0                 1877.0
25                        42.0                  614.0
26                        52.0                   89.0
27                        17.0                  105.0
28                        22.0                  221.0
29                        36.0                  671.0
30                        32.0                  275.0
31                        47.0                  292.0
32                        28.0                  592.0
33                        22.0                  113.0
34                        22.0                  188.0
35                        37.0                  120.0
36                        42.0                  213.0
37                        32.0                  155.0
38                        22.0                  185.0
39                        22.0                   89.0
40                        17.0                   72.0
41                        37.0                  257.0
42                        22.0                  166.0
43                        52.0                  247.0
44                        33.0                  713.0
45                        42.0                  210.0
46                        27.0                   64.0
47                        17.0                  197.0
48                        26.0                  662.0
49                        28.0                  646.0

    math_test_pct_prof_low_x  math_test_pct_prof_high_x  \
0                       41.0                       41.0
1                       44.0                       44.0
2                       65.0                       65.0
3                       73.0                       73.0
4                       35.0                       39.0
5                       45.0                       49.0
6                       74.0                       74.0
7                       40.0                       44.0
8                       25.0                       29.0
9                       25.0                       29.0
10                      65.0                       69.0
11                      60.0                       64.0
12                      40.0                       44.0
13                      70.0                       74.0
14                      30.0                       34.0
15                      80.0                       84.0
16                      51.0                       51.0
17                      55.0                       59.0
18                      75.0                       75.0
19                      47.0                       47.0
20                      54.0                       54.0
21                      20.0                       24.0
22                      20.0                       20.0
23                      35.0                       39.0
24                      21.0                       21.0
25                      53.0                       53.0
26                      60.0                       64.0
27                      25.0                       29.0
28                      30.0                       34.0
29                      45.0                       45.0
30                      45.0                       49.0
31                      50.0                       54.0
32                      39.0                       39.0
33                      25.0                       29.0
34                      30.0                       34.0
35                      40.0                       44.0
36                      50.0                       54.0
37                      35.0                       39.0
38                      25.0                       29.0
39                      35.0                       39.0
40                      20.0                       24.0
41                      45.0                       49.0
42                      40.0                       44.0
43                      75.0                       79.0
44                      45.0                       45.0
45                      50.0                       54.0
46                      20.0                       24.0
47                      20.0                       24.0
48                      42.0                       42.0
49                      48.0                       48.0

    math_test_pct_prof_midpt_x  read_test_num_valid_y  \
0                         41.0                  334.0
1                         44.0                  393.0
2                         65.0                 1138.0
3                         73.0                  778.0
4                         37.0                  118.0
5                         47.0                  173.0
6                         74.0                  345.0
7                         42.0                  236.0
8                         27.0                  124.0
9                         27.0                  136.0
10                        67.0                  186.0
11                        62.0                  270.0
12                        42.0                  173.0
13                        72.0                  222.0
14                        32.0                   78.0
15                        82.0                   98.0
16                        51.0                  478.0
17                        57.0                  283.0
18                        75.0                  626.0
19                        47.0                  788.0
20                        54.0                 2349.0
21                        22.0                   82.0
22                        20.0                  277.0
23                        37.0                  261.0
24                        21.0                 1683.0
25                        53.0                  669.0
26                        62.0                   80.0
27                        27.0                   98.0
28                        32.0                  220.0
29                        45.0                  780.0
30                        47.0                  275.0
31                        52.0                  305.0
32                        39.0                  600.0
33                        27.0                  141.0
34                        32.0                  255.0
35                        42.0                  175.0
36                        52.0                  184.0
37                        37.0                  159.0
38                        27.0                  198.0
39                        37.0                  110.0
40                        22.0                   70.0
41                        47.0                  246.0
42                        42.0                  184.0
43                        77.0                  225.0
44                        45.0                  800.0
45                        52.0                  270.0
46                        22.0                   92.0
47                        22.0                  272.0
48                        42.0                  703.0
49                        48.0                  646.0

    read_test_pct_prof_low_y  read_test_pct_prof_high_y  \
0                       36.0                       36.0
1                       42.0                       42.0
2                       67.0                       67.0
3                       67.0                       67.0
4                       50.0                       54.0
5                       40.0                       44.0
6                       55.0                       55.0
7                       45.0                       49.0
8                       50.0                       54.0
9                       30.0                       34.0
10                      70.0                       74.0
11                      45.0                       49.0
12                      30.0                       34.0
13                      50.0                       54.0
14                      30.0                       34.0
15                      50.0                       54.0
16                      50.0                       50.0
17                      50.0                       54.0
18                      64.0                       64.0
19                      58.0                       58.0
20                      45.0                       45.0
21                      20.0                       24.0
22                      15.0                       19.0
23                      35.0                       39.0
24                      30.0                       30.0
25                      34.0                       34.0
26                      50.0                       54.0
27                      20.0                       24.0
28                      30.0                       34.0
29                      45.0                       45.0
30                      35.0                       39.0
31                      38.0                       38.0
32                      44.0                       44.0
33                      20.0                       24.0
34                      30.0                       34.0
35                      40.0                       44.0
36                      50.0                       54.0
37                      35.0                       39.0
38                      35.0                       39.0
39                      30.0                       34.0
40                      45.0                       49.0
41                      40.0                       44.0
42                      45.0                       49.0
43                      75.0                       79.0
44                      49.0                       49.0
45                      50.0                       54.0
46                      25.0                       29.0
47                      20.0                       24.0
48                      38.0                       38.0
49                      45.0                       45.0

    read_test_pct_prof_midpt_y
0                         36.0
1                         42.0
2                         67.0
3                         67.0
4                         52.0
5                         42.0
6                         55.0
7                         47.0
8                         52.0
9                         32.0
10                        72.0
11                        47.0
12                        32.0
13                        52.0
14                        32.0
15                        52.0
16                        50.0
17                        52.0
18                        64.0
19                        58.0
20                        45.0
21                        22.0
22                        17.0
23                        37.0
24                        30.0
25                        34.0
26                        52.0
27                        22.0
28                        32.0
29                        45.0
30                        37.0
31                        38.0
32                        44.0
33                        22.0
34                        32.0
35                        42.0
36                        52.0
37                        37.0
38                        37.0
39                        32.0
40                        47.0
41                        42.0
42                        47.0
43                        77.0
44                        49.0
45                        52.0
46                        27.0
47                        22.0
48                        38.0
49                        45.0

### 3.3.2 Rename columns for clarity

In [40]:
scores.rename(columns= {'leaid':'ID Number', 'lea_name':'District Name', 'math_test_num_valid_y':'Number of 8th Grade Math Tests', 'math_test_num_valid_x':'Number of 4th Grade Math Tests', 'read_test_num_valid_y':'Number of 8th Grade Reading Tests', 'read_test_num_valid_x':'Number of 4th Grade Reading Tests', 'read_test_pct_prof_low_x':'4th Grade Reading Proficiency Percentage-low', 'read_test_pct_prof_high_x':'4th Grade Reading Proficiency Percentage-high', 'read_test_pct_prof_midpt_x':'4th Grade Reading Proficiency Percentage-mid', 'read_test_pct_prof_midpt_y':'8th Grade Reading Proficiency Percentage-mid', 'read_test_pct_prof_low_y':'8th Grade Reading Proficiency Percentage-low', 'read_test_pct_prof_high_y':'8th Grade Reading Proficiency Percentage-high', 'math_test_pct_prof_low_x':'4th Grade Math Proficiency Percentage-low', 'math_test_pct_prof_midpt_x':'4th Grade Math Proficiency Percentage-mid', 'math_test_pct_prof_high_x':'4th Grade Math Proficiency Percentage-high'}, inplace=True)
print(scores.head(50))

   ID Number  year     District Name  Number of 4th Grade Reading Tests  \
0    0100005  2014  Albertville City                              389.0
1    0100006  2014   Marshall County                              440.0
2    0100007  2014       Hoover City                             1011.0
3    0100008  2014      Madison City                              734.0
4    0100011  2014        Leeds City                              145.0
5    0100012  2014         Boaz City                              194.0
6    0100013  2014   Trussville City                              332.0
7    0100030  2014    Alexander City                              215.0
8    0100060  2014    Andalusia City                              121.0
9    0100090  2014     Anniston City                              156.0
10   0100100  2014         Arab City                              189.0
11   0100120  2014       Athens City                              254.0
12   0100180  2014      Attalla City                               80.0
13   0100185  2014     Saraland City                              208.0
14   0100188  2014    Chickasaw City                               63.0
15   0100189  2014      Satsuma City                               99.0
16   0100190  2014    Alabaster City                              466.0
17   0100194  2014       Pelham City                              256.0
18   0100210  2014       Auburn City                              643.0
19   0100240  2014    Autauga County                              728.0
20   0100270  2014    Baldwin County                             2341.0
21   0100300  2014    Barbour County                               66.0
22   0100330  2014     Bessemer City                              304.0
23   0100360  2014       Bibb County                              233.0
24   0100390  2014   Birmingham City                             1877.0
25   0100420  2014     Blount County                              614.0
26   0100450  2014      Brewton City                               89.0
27   0100480  2014    Bullock County                              104.0
28   0100510  2014     Butler County                              222.0
29   0100540  2014    Calhoun County                              671.0
30   0100600  2014   Chambers County                              275.0
31   0100630  2014   Cherokee County                              292.0
32   0100660  2014    Chilton County                              592.0
33   0100690  2014    Choctaw County                              112.0
34   0100720  2014     Clarke County                              189.0
35   0100750  2014       Clay County                              121.0
36   0100780  2014   Cleburne County                              213.0
37   0100810  2014     Coffee County                              155.0
38   0100840  2014    Colbert County                              185.0
39   0100870  2014    Conecuh County                               88.0
40   0100900  2014      Coosa County                               72.0
41   0100930  2014  Covington County                              257.0
42   0100960  2014   Crenshaw County                              145.0
43   0100990  2014      Cullman City                              246.0
44   0101020  2014    Cullman County                              711.0
45   0101050  2014       Dale County                              210.0
46   0101080  2014    Daleville City                               64.0
47   0101110  2014     Dallas County                              197.0
48   0101140  2014     Dekalb County                              660.0
49   0101170  2014      Decatur City                              642.0

    4th Grade Reading Proficiency Percentage-low  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           20.0
5                                           35.0
6                                           58.0
7                                           30.0
8                                           20.0
9                                           15.0
10                                          55.0
11                                          50.0
12                                          45.0
13                                          50.0
14                                          15.0
15                                          40.0
16                                          33.0
17                                          50.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          10.0
22                                          12.0
23                                          30.0
24                                          15.0
25                                          42.0
26                                          50.0
27                                          15.0
28                                          20.0
29                                          36.0
30                                          30.0
31                                          45.0
32                                          28.0
33                                          20.0
34                                          20.0
35                                          35.0
36                                          40.0
37                                          30.0
38                                          20.0
39                                          20.0
40                                          15.0
41                                          35.0
42                                          20.0
43                                          50.0
44                                          33.0
45                                          40.0
46                                          25.0
47                                          15.0
48                                          26.0
49                                          28.0

    4th Grade Reading Proficiency Percentage-high  \
0                                            31.0
1                                            29.0
2                                            56.0
3                                            70.0
4                                            24.0
5                                            39.0
6                                            58.0
7                                            34.0
8                                            24.0
9                                            19.0
10                                           59.0
11                                           54.0
12                                           49.0
13                                           54.0
14                                           19.0
15                                           44.0
16                                           33.0
17                                           54.0
18                                           56.0
19                                           36.0
20                                           36.0
21                                           14.0
22                                           12.0
23                                           34.0
24                                           15.0
25                                           42.0
26                                           54.0
27                                           19.0
28                                           24.0
29                                           36.0
30                                           34.0
31                                           49.0
32                                           28.0
33                                           24.0
34                                           24.0
35                                           39.0
36                                           44.0
37                                           34.0
38                                           24.0
39                                           24.0
40                                           19.0
41                                           39.0
42                                           24.0
43                                           54.0
44                                           33.0
45                                           44.0
46                                           29.0
47                                           19.0
48                                           26.0
49                                           28.0

    4th Grade Reading Proficiency Percentage-mid  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           22.0
5                                           37.0
6                                           58.0
7                                           32.0
8                                           22.0
9                                           17.0
10                                          57.0
11                                          52.0
12                                          47.0
13                                          52.0
14                                          17.0
15                                          42.0
16                                          33.0
17                                          52.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          12.0
22                                          12.0
23                                          32.0
24                                          15.0
25                                          42.0
26                                          52.0
27                                          17.0
28                                          22.0
29                                          36.0
30                                          32.0
31                                          47.0
32                                          28.0
33                                          22.0
34                                          22.0
35                                          37.0
36                                          42.0
37                                          32.0
38                                          22.0
39                                          22.0
40                                          17.0
41                                          37.0
42                                          22.0
43                                          52.0
44                                          33.0
45                                          42.0
46                                          27.0
47                                          17.0
48                                          26.0
49                                          28.0

    Number of 4th Grade Math Tests  4th Grade Math Proficiency Percentage-low  \
0                            392.0                                       41.0
1                            440.0                                       44.0
2                           1011.0                                       65.0
3                            736.0                                       73.0
4                            146.0                                       35.0
5                            197.0                                       45.0
6                            333.0                                       74.0
7                            217.0                                       40.0
8                            121.0                                       25.0
9                            156.0                                       25.0
10                           189.0                                       65.0
11                           254.0                                       60.0
12                            80.0                                       40.0
13                           209.0                                       70.0
14                            63.0                                       30.0
15                            99.0                                       80.0
16                           465.0                                       51.0
17                           257.0                                       55.0
18                           648.0                                       75.0
19                           726.0                                       47.0
20                          2339.0                                       54.0
21                            66.0                                       20.0
22                           305.0                                       20.0
23                           233.0                                       35.0
24                          1877.0                                       21.0
25                           614.0                                       53.0
26                            89.0                                       60.0
27                           105.0                                       25.0
28                           221.0                                       30.0
29                           671.0                                       45.0
30                           275.0                                       45.0
31                           292.0                                       50.0
32                           592.0                                       39.0
33                           113.0                                       25.0
34                           188.0                                       30.0
35                           120.0                                       40.0
36                           213.0                                       50.0
37                           155.0                                       35.0
38                           185.0                                       25.0
39                            89.0                                       35.0
40                            72.0                                       20.0
41                           257.0                                       45.0
42                           166.0                                       40.0
43                           247.0                                       75.0
44                           713.0                                       45.0
45                           210.0                                       50.0
46                            64.0                                       20.0
47                           197.0                                       20.0
48                           662.0                                       42.0
49                           646.0                                       48.0

    4th Grade Math Proficiency Percentage-high  \
0                                         41.0
1                                         44.0
2                                         65.0
3                                         73.0
4                                         39.0
5                                         49.0
6                                         74.0
7                                         44.0
8                                         29.0
9                                         29.0
10                                        69.0
11                                        64.0
12                                        44.0
13                                        74.0
14                                        34.0
15                                        84.0
16                                        51.0
17                                        59.0
18                                        75.0
19                                        47.0
20                                        54.0
21                                        24.0
22                                        20.0
23                                        39.0
24                                        21.0
25                                        53.0
26                                        64.0
27                                        29.0
28                                        34.0
29                                        45.0
30                                        49.0
31                                        54.0
32                                        39.0
33                                        29.0
34                                        34.0
35                                        44.0
36                                        54.0
37                                        39.0
38                                        29.0
39                                        39.0
40                                        24.0
41                                        49.0
42                                        44.0
43                                        79.0
44                                        45.0
45                                        54.0
46                                        24.0
47                                        24.0
48                                        42.0
49                                        48.0

    4th Grade Math Proficiency Percentage-mid  \
0                                        41.0
1                                        44.0
2                                        65.0
3                                        73.0
4                                        37.0
5                                        47.0
6                                        74.0
7                                        42.0
8                                        27.0
9                                        27.0
10                                       67.0
11                                       62.0
12                                       42.0
13                                       72.0
14                                       32.0
15                                       82.0
16                                       51.0
17                                       57.0
18                                       75.0
19                                       47.0
20                                       54.0
21                                       22.0
22                                       20.0
23                                       37.0
24                                       21.0
25                                       53.0
26                                       62.0
27                                       27.0
28                                       32.0
29                                       45.0
30                                       47.0
31                                       52.0
32                                       39.0
33                                       27.0
34                                       32.0
35                                       42.0
36                                       52.0
37                                       37.0
38                                       27.0
39                                       37.0
40                                       22.0
41                                       47.0
42                                       42.0
43                                       77.0
44                                       45.0
45                                       52.0
46                                       22.0
47                                       22.0
48                                       42.0
49                                       48.0


In [41]:
print(scores.tail(20))

      ID Number  year                    District Name  \
10713   3904935  2014                    Leipsic Local
10714   3904936  2014  Miller City-New Cleveland Local
10715   3904937  2014            Ottawa-Glandorf Local
10716   3904938  2014                  Ottoville Local
10717   3904939  2014             Pandora-Gilboa Local
10718   3904941  2014          Clear Fork Valley Local
10719   3904942  2014                  Crestview Local
10720   3904943  2014                  Lexington Local
10721   3904944  2014                      Lucas Local
10722   3904945  2014                    Madison Local
10723   3904946  2014            Plymouth-Shiloh Local
10724   3904947  2014                    Ontario Local
10725   3904949  2014                      Adena Local
10726   3904950  2014                 Huntington Local
10727   3904951  2014               Paint Valley Local
10728   3904952  2014               Southeastern Local
10729   3904953  2014               Union-Scioto Local
10730   3904954  2014                 Zane Trace Local
10731   3904956  2014                     Lakota Local
10732   3904957  2014                   Woodmore Local

       Number of 4th Grade Reading Tests  \
10713                                NaN
10714                                NaN
10715                                NaN
10716                                NaN
10717                                NaN
10718                                NaN
10719                                NaN
10720                                NaN
10721                                NaN
10722                                NaN
10723                                NaN
10724                                NaN
10725                                NaN
10726                                NaN
10727                                NaN
10728                                NaN
10729                                NaN
10730                                NaN
10731                                NaN
10732                                NaN

       4th Grade Reading Proficiency Percentage-low  \
10713                                           NaN
10714                                           NaN
10715                                           NaN
10716                                           NaN
10717                                           NaN
10718                                           NaN
10719                                           NaN
10720                                           NaN
10721                                           NaN
10722                                           NaN
10723                                           NaN
10724                                           NaN
10725                                           NaN
10726                                           NaN
10727                                           NaN
10728                                           NaN
10729                                           NaN
10730                                           NaN
10731                                           NaN
10732                                           NaN

       4th Grade Reading Proficiency Percentage-high  \
10713                                            NaN
10714                                            NaN
10715                                            NaN
10716                                            NaN
10717                                            NaN
10718                                            NaN
10719                                            NaN
10720                                            NaN
10721                                            NaN
10722                                            NaN
10723                                            NaN
10724                                            NaN
10725                                            NaN
10726                                            NaN
10727                                            NaN
10728                                            NaN
10729                                            NaN
10730                                            NaN
10731                                            NaN
10732                                            NaN

       4th Grade Reading Proficiency Percentage-mid  \
10713                                           NaN
10714                                           NaN
10715                                           NaN
10716                                           NaN
10717                                           NaN
10718                                           NaN
10719                                           NaN
10720                                           NaN
10721                                           NaN
10722                                           NaN
10723                                           NaN
10724                                           NaN
10725                                           NaN
10726                                           NaN
10727                                           NaN
10728                                           NaN
10729                                           NaN
10730                                           NaN
10731                                           NaN
10732                                           NaN

       Number of 4th Grade Math Tests  \
10713                             NaN
10714                             NaN
10715                             NaN
10716                             NaN
10717                             NaN
10718                             NaN
10719                             NaN
10720                             NaN
10721                             NaN
10722                             NaN
10723                             NaN
10724                             NaN
10725                             NaN
10726                             NaN
10727                             NaN
10728                             NaN
10729                             NaN
10730                             NaN
10731                             NaN
10732                             NaN

       4th Grade Math Proficiency Percentage-low  \
10713                                        NaN
10714                                        NaN
10715                                        NaN
10716                                        NaN
10717                                        NaN
10718                                        NaN
10719                                        NaN
10720                                        NaN
10721                                        NaN
10722                                        NaN
10723                                        NaN
10724                                        NaN
10725                                        NaN
10726                                        NaN
10727                                        NaN
10728                                        NaN
10729                                        NaN
10730                                        NaN
10731                                        NaN
10732                                        NaN

       4th Grade Math Proficiency Percentage-high  \
10713                                         NaN
10714                                         NaN
10715                                         NaN
10716                                         NaN
10717                                         NaN
10718                                         NaN
10719                                         NaN
10720                                         NaN
10721                                         NaN
10722                                         NaN
10723                                         NaN
10724                                         NaN
10725                                         NaN
10726                                         NaN
10727                                         NaN
10728                                         NaN
10729                                         NaN
10730                                         NaN
10731                                         NaN
10732                                         NaN

       4th Grade Math Proficiency Percentage-mid  \
10713                                        NaN
10714                                        NaN
10715                                        NaN
10716                                        NaN
10717                                        NaN
10718                                        NaN
10719                                        NaN
10720                                        NaN
10721                                        NaN
10722                                        NaN
10723                                        NaN
10724                                        NaN
10725                                        NaN
10726                                        NaN
10727                                        NaN
10728                                        NaN
10729                                        NaN
10730                                        NaN
10731                                        NaN
10732                                        NaN

       Number of 8th Grade Reading Tests  \
10713                               55.0
10714                               32.0
10715                               93.0
10716                               24.0
10717                               41.0
10718                              141.0
10719                               87.0
10720                              226.0
10721                               51.0
10722                              231.0
10723                               71.0
10724                              150.0
10725                               93.0
10726                               95.0
10727                               87.0
10728                               87.0
10729                              160.0
10730                              109.0
10731                               78.0
10732                               85.0

       8th Grade Reading Proficiency Percentage-low  \
10713                                          50.0
10714                                          80.0
10715                                          80.0
10716                                          60.0
10717                                          80.0
10718                                          65.0
10719                                          80.0
10720                                          70.0
10721                                          70.0
10722                                          55.0
10723                                          65.0
10724                                          85.0
10725                                          70.0
10726                                          50.0
10727                                          50.0
10728                                          70.0
10729                                          55.0
10730                                          70.0
10731                                          60.0
10732                                          85.0

       8th Grade Reading Proficiency Percentage-high  \
10713                                           59.0
10714                                           89.0
10715                                           84.0
10716                                           79.0
10717                                           89.0
10718                                           69.0
10719                                           84.0
10720                                           74.0
10721                                           79.0
10722                                           59.0
10723                                           69.0
10724                                           89.0
10725                                           74.0
10726                                           54.0
10727                                           54.0
10728                                           74.0
10729                                           59.0
10730                                           74.0
10731                                           64.0
10732                                           89.0

       8th Grade Reading Proficiency Percentage-mid
10713                                          54.5
10714                                          84.5
10715                                          82.0
10716                                          69.5
10717                                          84.5
10718                                          67.0
10719                                          82.0
10720                                          72.0
10721                                          74.5
10722                                          57.0
10723                                          67.0
10724                                          87.0
10725                                          72.0
10726                                          52.0
10727                                          52.0
10728                                          72.0
10729                                          57.0
10730                                          72.0
10731                                          62.0
10732                                          87.0

### 3.3.3 Only keep scores that are non-negative

In [42]:
scores = scores[scores['8th Grade Reading Proficiency Percentage-low'] >= 0]
scores = scores[scores['8th Grade Reading Proficiency Percentage-high'] >= 0]
scores = scores[scores['8th Grade Reading Proficiency Percentage-mid'] >= 0]
print(scores.head(50))

   ID Number  year     District Name  Number of 4th Grade Reading Tests  \
0    0100005  2014  Albertville City                              389.0
1    0100006  2014   Marshall County                              440.0
2    0100007  2014       Hoover City                             1011.0
3    0100008  2014      Madison City                              734.0
4    0100011  2014        Leeds City                              145.0
5    0100012  2014         Boaz City                              194.0
6    0100013  2014   Trussville City                              332.0
7    0100030  2014    Alexander City                              215.0
8    0100060  2014    Andalusia City                              121.0
9    0100090  2014     Anniston City                              156.0
10   0100100  2014         Arab City                              189.0
11   0100120  2014       Athens City                              254.0
12   0100180  2014      Attalla City                               80.0
13   0100185  2014     Saraland City                              208.0
14   0100188  2014    Chickasaw City                               63.0
15   0100189  2014      Satsuma City                               99.0
16   0100190  2014    Alabaster City                              466.0
17   0100194  2014       Pelham City                              256.0
18   0100210  2014       Auburn City                              643.0
19   0100240  2014    Autauga County                              728.0
20   0100270  2014    Baldwin County                             2341.0
21   0100300  2014    Barbour County                               66.0
22   0100330  2014     Bessemer City                              304.0
23   0100360  2014       Bibb County                              233.0
24   0100390  2014   Birmingham City                             1877.0
25   0100420  2014     Blount County                              614.0
26   0100450  2014      Brewton City                               89.0
27   0100480  2014    Bullock County                              104.0
28   0100510  2014     Butler County                              222.0
29   0100540  2014    Calhoun County                              671.0
30   0100600  2014   Chambers County                              275.0
31   0100630  2014   Cherokee County                              292.0
32   0100660  2014    Chilton County                              592.0
33   0100690  2014    Choctaw County                              112.0
34   0100720  2014     Clarke County                              189.0
35   0100750  2014       Clay County                              121.0
36   0100780  2014   Cleburne County                              213.0
37   0100810  2014     Coffee County                              155.0
38   0100840  2014    Colbert County                              185.0
39   0100870  2014    Conecuh County                               88.0
40   0100900  2014      Coosa County                               72.0
41   0100930  2014  Covington County                              257.0
42   0100960  2014   Crenshaw County                              145.0
43   0100990  2014      Cullman City                              246.0
44   0101020  2014    Cullman County                              711.0
45   0101050  2014       Dale County                              210.0
46   0101080  2014    Daleville City                               64.0
47   0101110  2014     Dallas County                              197.0
48   0101140  2014     Dekalb County                              660.0
49   0101170  2014      Decatur City                              642.0

    4th Grade Reading Proficiency Percentage-low  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           20.0
5                                           35.0
6                                           58.0
7                                           30.0
8                                           20.0
9                                           15.0
10                                          55.0
11                                          50.0
12                                          45.0
13                                          50.0
14                                          15.0
15                                          40.0
16                                          33.0
17                                          50.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          10.0
22                                          12.0
23                                          30.0
24                                          15.0
25                                          42.0
26                                          50.0
27                                          15.0
28                                          20.0
29                                          36.0
30                                          30.0
31                                          45.0
32                                          28.0
33                                          20.0
34                                          20.0
35                                          35.0
36                                          40.0
37                                          30.0
38                                          20.0
39                                          20.0
40                                          15.0
41                                          35.0
42                                          20.0
43                                          50.0
44                                          33.0
45                                          40.0
46                                          25.0
47                                          15.0
48                                          26.0
49                                          28.0

    4th Grade Reading Proficiency Percentage-high  \
0                                            31.0
1                                            29.0
2                                            56.0
3                                            70.0
4                                            24.0
5                                            39.0
6                                            58.0
7                                            34.0
8                                            24.0
9                                            19.0
10                                           59.0
11                                           54.0
12                                           49.0
13                                           54.0
14                                           19.0
15                                           44.0
16                                           33.0
17                                           54.0
18                                           56.0
19                                           36.0
20                                           36.0
21                                           14.0
22                                           12.0
23                                           34.0
24                                           15.0
25                                           42.0
26                                           54.0
27                                           19.0
28                                           24.0
29                                           36.0
30                                           34.0
31                                           49.0
32                                           28.0
33                                           24.0
34                                           24.0
35                                           39.0
36                                           44.0
37                                           34.0
38                                           24.0
39                                           24.0
40                                           19.0
41                                           39.0
42                                           24.0
43                                           54.0
44                                           33.0
45                                           44.0
46                                           29.0
47                                           19.0
48                                           26.0
49                                           28.0

    4th Grade Reading Proficiency Percentage-mid  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           22.0
5                                           37.0
6                                           58.0
7                                           32.0
8                                           22.0
9                                           17.0
10                                          57.0
11                                          52.0
12                                          47.0
13                                          52.0
14                                          17.0
15                                          42.0
16                                          33.0
17                                          52.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          12.0
22                                          12.0
23                                          32.0
24                                          15.0
25                                          42.0
26                                          52.0
27                                          17.0
28                                          22.0
29                                          36.0
30                                          32.0
31                                          47.0
32                                          28.0
33                                          22.0
34                                          22.0
35                                          37.0
36                                          42.0
37                                          32.0
38                                          22.0
39                                          22.0
40                                          17.0
41                                          37.0
42                                          22.0
43                                          52.0
44                                          33.0
45                                          42.0
46                                          27.0
47                                          17.0
48                                          26.0
49                                          28.0

    Number of 4th Grade Math Tests  4th Grade Math Proficiency Percentage-low  \
0                            392.0                                       41.0
1                            440.0                                       44.0
2                           1011.0                                       65.0
3                            736.0                                       73.0
4                            146.0                                       35.0
5                            197.0                                       45.0
6                            333.0                                       74.0
7                            217.0                                       40.0
8                            121.0                                       25.0
9                            156.0                                       25.0
10                           189.0                                       65.0
11                           254.0                                       60.0
12                            80.0                                       40.0
13                           209.0                                       70.0
14                            63.0                                       30.0
15                            99.0                                       80.0
16                           465.0                                       51.0
17                           257.0                                       55.0
18                           648.0                                       75.0
19                           726.0                                       47.0
20                          2339.0                                       54.0
21                            66.0                                       20.0
22                           305.0                                       20.0
23                           233.0                                       35.0
24                          1877.0                                       21.0
25                           614.0                                       53.0
26                            89.0                                       60.0
27                           105.0                                       25.0
28                           221.0                                       30.0
29                           671.0                                       45.0
30                           275.0                                       45.0
31                           292.0                                       50.0
32                           592.0                                       39.0
33                           113.0                                       25.0
34                           188.0                                       30.0
35                           120.0                                       40.0
36                           213.0                                       50.0
37                           155.0                                       35.0
38                           185.0                                       25.0
39                            89.0                                       35.0
40                            72.0                                       20.0
41                           257.0                                       45.0
42                           166.0                                       40.0
43                           247.0                                       75.0
44                           713.0                                       45.0
45                           210.0                                       50.0
46                            64.0                                       20.0
47                           197.0                                       20.0
48                           662.0                                       42.0
49                           646.0                                       48.0

    4th Grade Math Proficiency Percentage-high  \
0                                         41.0
1                                         44.0
2                                         65.0
3                                         73.0
4                                         39.0
5                                         49.0
6                                         74.0
7                                         44.0
8                                         29.0
9                                         29.0
10                                        69.0
11                                        64.0
12                                        44.0
13                                        74.0
14                                        34.0
15                                        84.0
16                                        51.0
17                                        59.0
18                                        75.0
19                                        47.0
20                                        54.0
21                                        24.0
22                                        20.0
23                                        39.0
24                                        21.0
25                                        53.0
26                                        64.0
27                                        29.0
28                                        34.0
29                                        45.0
30                                        49.0
31                                        54.0
32                                        39.0
33                                        29.0
34                                        34.0
35                                        44.0
36                                        54.0
37                                        39.0
38                                        29.0
39                                        39.0
40                                        24.0
41                                        49.0
42                                        44.0
43                                        79.0
44                                        45.0
45                                        54.0
46                                        24.0
47                                        24.0
48                                        42.0
49                                        48.0

    4th Grade Math Proficiency Percentage-mid  \
0                                        41.0
1                                        44.0
2                                        65.0
3                                        73.0
4                                        37.0
5                                        47.0
6                                        74.0
7                                        42.0
8                                        27.0
9                                        27.0
10                                       67.0
11                                       62.0
12                                       42.0
13                                       72.0
14                                       32.0
15                                       82.0
16                                       51.0
17                                       57.0
18                                       75.0
19                                       47.0
20                                       54.0
21                                       22.0
22                                       20.0
23                                       37.0
24                                       21.0
25                                       53.0
26                                       62.0
27                                       27.0
28                                       32.0
29                                       45.0
30                                       47.0
31                                       52.0
32                                       39.0
33                                       27.0
34                                       32.0
35                                       42.0
36                                       52.0
37                                       37.0
38                                       27.0
39                                       37.0
40                                       22.0
41                                       47.0
42                                       42.0
43                                       77.0
44                                       45.0
45                                       52.0
46                                       22.0
47                                       22.0
48                                       42.0
49                                       48.0


In [43]:
scores = scores[scores['4th Grade Reading Proficiency Percentage-low'] >= 0]
scores = scores[scores['4th Grade Reading Proficiency Percentage-high'] >= 0]
scores = scores[scores['4th Grade Reading Proficiency Percentage-mid'] >= 0]
print(scores.head(50))

   ID Number  year     District Name  Number of 4th Grade Reading Tests  \
0    0100005  2014  Albertville City                              389.0
1    0100006  2014   Marshall County                              440.0
2    0100007  2014       Hoover City                             1011.0
3    0100008  2014      Madison City                              734.0
4    0100011  2014        Leeds City                              145.0
5    0100012  2014         Boaz City                              194.0
6    0100013  2014   Trussville City                              332.0
7    0100030  2014    Alexander City                              215.0
8    0100060  2014    Andalusia City                              121.0
9    0100090  2014     Anniston City                              156.0
10   0100100  2014         Arab City                              189.0
11   0100120  2014       Athens City                              254.0
12   0100180  2014      Attalla City                               80.0
13   0100185  2014     Saraland City                              208.0
14   0100188  2014    Chickasaw City                               63.0
15   0100189  2014      Satsuma City                               99.0
16   0100190  2014    Alabaster City                              466.0
17   0100194  2014       Pelham City                              256.0
18   0100210  2014       Auburn City                              643.0
19   0100240  2014    Autauga County                              728.0
20   0100270  2014    Baldwin County                             2341.0
21   0100300  2014    Barbour County                               66.0
22   0100330  2014     Bessemer City                              304.0
23   0100360  2014       Bibb County                              233.0
24   0100390  2014   Birmingham City                             1877.0
25   0100420  2014     Blount County                              614.0
26   0100450  2014      Brewton City                               89.0
27   0100480  2014    Bullock County                              104.0
28   0100510  2014     Butler County                              222.0
29   0100540  2014    Calhoun County                              671.0
30   0100600  2014   Chambers County                              275.0
31   0100630  2014   Cherokee County                              292.0
32   0100660  2014    Chilton County                              592.0
33   0100690  2014    Choctaw County                              112.0
34   0100720  2014     Clarke County                              189.0
35   0100750  2014       Clay County                              121.0
36   0100780  2014   Cleburne County                              213.0
37   0100810  2014     Coffee County                              155.0
38   0100840  2014    Colbert County                              185.0
39   0100870  2014    Conecuh County                               88.0
40   0100900  2014      Coosa County                               72.0
41   0100930  2014  Covington County                              257.0
42   0100960  2014   Crenshaw County                              145.0
43   0100990  2014      Cullman City                              246.0
44   0101020  2014    Cullman County                              711.0
45   0101050  2014       Dale County                              210.0
46   0101080  2014    Daleville City                               64.0
47   0101110  2014     Dallas County                              197.0
48   0101140  2014     Dekalb County                              660.0
49   0101170  2014      Decatur City                              642.0

    4th Grade Reading Proficiency Percentage-low  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           20.0
5                                           35.0
6                                           58.0
7                                           30.0
8                                           20.0
9                                           15.0
10                                          55.0
11                                          50.0
12                                          45.0
13                                          50.0
14                                          15.0
15                                          40.0
16                                          33.0
17                                          50.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          10.0
22                                          12.0
23                                          30.0
24                                          15.0
25                                          42.0
26                                          50.0
27                                          15.0
28                                          20.0
29                                          36.0
30                                          30.0
31                                          45.0
32                                          28.0
33                                          20.0
34                                          20.0
35                                          35.0
36                                          40.0
37                                          30.0
38                                          20.0
39                                          20.0
40                                          15.0
41                                          35.0
42                                          20.0
43                                          50.0
44                                          33.0
45                                          40.0
46                                          25.0
47                                          15.0
48                                          26.0
49                                          28.0

    4th Grade Reading Proficiency Percentage-high  \
0                                            31.0
1                                            29.0
2                                            56.0
3                                            70.0
4                                            24.0
5                                            39.0
6                                            58.0
7                                            34.0
8                                            24.0
9                                            19.0
10                                           59.0
11                                           54.0
12                                           49.0
13                                           54.0
14                                           19.0
15                                           44.0
16                                           33.0
17                                           54.0
18                                           56.0
19                                           36.0
20                                           36.0
21                                           14.0
22                                           12.0
23                                           34.0
24                                           15.0
25                                           42.0
26                                           54.0
27                                           19.0
28                                           24.0
29                                           36.0
30                                           34.0
31                                           49.0
32                                           28.0
33                                           24.0
34                                           24.0
35                                           39.0
36                                           44.0
37                                           34.0
38                                           24.0
39                                           24.0
40                                           19.0
41                                           39.0
42                                           24.0
43                                           54.0
44                                           33.0
45                                           44.0
46                                           29.0
47                                           19.0
48                                           26.0
49                                           28.0

    4th Grade Reading Proficiency Percentage-mid  \
0                                           31.0
1                                           29.0
2                                           56.0
3                                           70.0
4                                           22.0
5                                           37.0
6                                           58.0
7                                           32.0
8                                           22.0
9                                           17.0
10                                          57.0
11                                          52.0
12                                          47.0
13                                          52.0
14                                          17.0
15                                          42.0
16                                          33.0
17                                          52.0
18                                          56.0
19                                          36.0
20                                          36.0
21                                          12.0
22                                          12.0
23                                          32.0
24                                          15.0
25                                          42.0
26                                          52.0
27                                          17.0
28                                          22.0
29                                          36.0
30                                          32.0
31                                          47.0
32                                          28.0
33                                          22.0
34                                          22.0
35                                          37.0
36                                          42.0
37                                          32.0
38                                          22.0
39                                          22.0
40                                          17.0
41                                          37.0
42                                          22.0
43                                          52.0
44                                          33.0
45                                          42.0
46                                          27.0
47                                          17.0
48                                          26.0
49                                          28.0

    Number of 4th Grade Math Tests  4th Grade Math Proficiency Percentage-low  \
0                            392.0                                       41.0
1                            440.0                                       44.0
2                           1011.0                                       65.0
3                            736.0                                       73.0
4                            146.0                                       35.0
5                            197.0                                       45.0
6                            333.0                                       74.0
7                            217.0                                       40.0
8                            121.0                                       25.0
9                            156.0                                       25.0
10                           189.0                                       65.0
11                           254.0                                       60.0
12                            80.0                                       40.0
13                           209.0                                       70.0
14                            63.0                                       30.0
15                            99.0                                       80.0
16                           465.0                                       51.0
17                           257.0                                       55.0
18                           648.0                                       75.0
19                           726.0                                       47.0
20                          2339.0                                       54.0
21                            66.0                                       20.0
22                           305.0                                       20.0
23                           233.0                                       35.0
24                          1877.0                                       21.0
25                           614.0                                       53.0
26                            89.0                                       60.0
27                           105.0                                       25.0
28                           221.0                                       30.0
29                           671.0                                       45.0
30                           275.0                                       45.0
31                           292.0                                       50.0
32                           592.0                                       39.0
33                           113.0                                       25.0
34                           188.0                                       30.0
35                           120.0                                       40.0
36                           213.0                                       50.0
37                           155.0                                       35.0
38                           185.0                                       25.0
39                            89.0                                       35.0
40                            72.0                                       20.0
41                           257.0                                       45.0
42                           166.0                                       40.0
43                           247.0                                       75.0
44                           713.0                                       45.0
45                           210.0                                       50.0
46                            64.0                                       20.0
47                           197.0                                       20.0
48                           662.0                                       42.0
49                           646.0                                       48.0

    4th Grade Math Proficiency Percentage-high  \
0                                         41.0
1                                         44.0
2                                         65.0
3                                         73.0
4                                         39.0
5                                         49.0
6                                         74.0
7                                         44.0
8                                         29.0
9                                         29.0
10                                        69.0
11                                        64.0
12                                        44.0
13                                        74.0
14                                        34.0
15                                        84.0
16                                        51.0
17                                        59.0
18                                        75.0
19                                        47.0
20                                        54.0
21                                        24.0
22                                        20.0
23                                        39.0
24                                        21.0
25                                        53.0
26                                        64.0
27                                        29.0
28                                        34.0
29                                        45.0
30                                        49.0
31                                        54.0
32                                        39.0
33                                        29.0
34                                        34.0
35                                        44.0
36                                        54.0
37                                        39.0
38                                        29.0
39                                        39.0
40                                        24.0
41                                        49.0
42                                        44.0
43                                        79.0
44                                        45.0
45                                        54.0
46                                        24.0
47                                        24.0
48                                        42.0
49                                        48.0

    4th Grade Math Proficiency Percentage-mid  \
0                                        41.0
1                                        44.0
2                                        65.0
3                                        73.0
4                                        37.0
5                                        47.0
6                                        74.0
7                                        42.0
8                                        27.0
9                                        27.0
10                                       67.0
11                                       62.0
12                                       42.0
13                                       72.0
14                                       32.0
15                                       82.0
16                                       51.0
17                                       57.0
18                                       75.0
19                                       47.0
20                                       54.0
21                                       22.0
22                                       20.0
23                                       37.0
24                                       21.0
25                                       53.0
26                                       62.0
27                                       27.0
28                                       32.0
29                                       45.0
30                                       47.0
31                                       52.0
32                                       39.0
33                                       27.0
34                                       32.0
35                                       42.0
36                                       52.0
37                                       37.0
38                                       27.0
39                                       37.0
40                                       22.0
41                                       47.0
42                                       42.0
43                                       77.0
44                                       45.0
45                                       52.0
46                                       22.0
47                                       22.0
48                                       42.0
49                                       48.0


### 3.3.4 Duplicated information

While scores and years could be the same as for other schools, we want to check that there is only one row for each district.

In [44]:
duplicateRows = scores[scores.duplicated(["District Name"])]
print(duplicateRows)

     ID Number  year                        District Name  \
757    0507320  2014        HARMONY GROVE SCHOOL DISTRICT
1252   0618870  2014                 Jefferson Elementary
1296   0620790  2014            Lakeside Union Elementary
1405   0626220  2014             Mountain View Elementary
1443   0628170  2014                           Ocean View
...        ...   ...                                  ...
8239   3415870  2014            Stratford School District
8276   3417130  2014  Washington Township School District
9629   3900043  2014                    Riverside Academy
9802   3904352  2014                          Athens City
9931   3904492  2014                            Troy City

      Number of 4th Grade Reading Tests  \
757                                85.0
1252                              671.0
1296                              546.0
1405                              284.0
1443                              302.0
...                                 ...
8239                               87.0
8276                              214.0
9629                               30.0
9802                              175.0
9931                              287.0

      4th Grade Reading Proficiency Percentage-low  \
757                                           20.0
1252                                          40.0
1296                                          42.0
1405                                          40.0
1443                                          16.0
...                                            ...
8239                                          45.0
8276                                          65.0
9629                                           0.0
9802                                          75.0
9931                                          65.0

      4th Grade Reading Proficiency Percentage-high  \
757                                            24.0
1252                                           40.0
1296                                           42.0
1405                                           44.0
1443                                           16.0
...                                             ...
8239                                           49.0
8276                                           69.0
9629                                           20.0
9802                                           79.0
9931                                           69.0

      4th Grade Reading Proficiency Percentage-mid  \
757                                           22.0
1252                                          40.0
1296                                          42.0
1405                                          42.0
1443                                          16.0
...                                            ...
8239                                          47.0
8276                                          67.0
9629                                          10.0
9802                                          77.0
9931                                          67.0

      Number of 4th Grade Math Tests  \
757                             85.0
1252                           686.0
1296                           548.0
1405                           284.0
1443                           302.0
...                              ...
8239                            87.0
8276                           214.0
9629                            30.0
9802                           176.0
9931                           287.0

      4th Grade Math Proficiency Percentage-low  \
757                                        25.0
1252                                       37.0
1296                                       33.0
1405                                       25.0
1443                                       10.0
...                                         ...
8239                                       30.0
8276                                       60.0
9629                                        0.0
9802                                       55.0
9931                                       70.0

      4th Grade Math Proficiency Percentage-high  \
757                                         29.0
1252                                        37.0
1296                                        33.0
1405                                        29.0
1443                                        10.0
...                                          ...
8239                                        34.0
8276                                        64.0
9629                                        20.0
9802                                        59.0
9931                                        74.0

      4th Grade Math Proficiency Percentage-mid  \
757                                        27.0
1252                                       37.0
1296                                       33.0
1405                                       27.0
1443                                       10.0
...                                         ...
8239                                       32.0
8276                                       62.0
9629                                       10.0
9802                                       57.0
9931                                       72.0

      Number of 8th Grade Reading Tests  \
757                                91.0
1252                              701.0
1296                              393.0
1405                              313.0
1443                              251.0
...                                 ...
8239                              122.0
8276                              248.0
9629                               27.0
9802                              212.0
9931                              359.0

      8th Grade Reading Proficiency Percentage-low  \
757                                           20.0
1252                                          45.0
1296                                          48.0
1405                                          52.0
1443                                          25.0
...                                            ...
8239                                          45.0
8276                                          60.0
9629                                          21.0
9802                                          80.0
9931                                          74.0

      8th Grade Reading Proficiency Percentage-high  \
757                                            24.0
1252                                           45.0
1296                                           48.0
1405                                           52.0
1443                                           29.0
...                                             ...
8239                                           49.0
8276                                           64.0
9629                                           39.0
9802                                           84.0
9931                                           74.0

      8th Grade Reading Proficiency Percentage-mid
757                                           22.0
1252                                          45.0
1296                                          48.0
1405                                          52.0
1443                                          27.0
...                                            ...
8239                                          47.0
8276                                          62.0
9629                                          30.0
9802                                          82.0
9931                                          74.0

[118 rows x 15 columns]

The above shows 259 Rows have district names that are duplicates.  However, knowing that some states may have districts with the same name as districts in other states, and with this dataset not containing district information, we'll check the ID numbers to verify whether these are true duplicates.

In [45]:
duplicateRows = scores[scores.duplicated(["ID Number"])]
print(duplicateRows)

Empty DataFrame
Columns: [ID Number, year, District Name, Number of 4th Grade Reading Tests, 4th Grade Reading Proficiency Percentage-low, 4th Grade Reading Proficiency Percentage-high, 4th Grade Reading Proficiency Percentage-mid, Number of 4th Grade Math Tests, 4th Grade Math Proficiency Percentage-low, 4th Grade Math Proficiency Percentage-high, 4th Grade Math Proficiency Percentage-mid, Number of 8th Grade Reading Tests, 8th Grade Reading Proficiency Percentage-low, 8th Grade Reading Proficiency Percentage-high, 8th Grade Reading Proficiency Percentage-mid]
Index: []

Checking for duplicates by ID number results in an empty dataframe.  Therefore, we can conclude that the ID numbers for each district in our dataset are unique.

### 3.3.5 Missing Values

In [46]:
missing = scores[scores.isna().any(axis=1)]
print(missing)

     ID Number  year                                   District Name  \
8537   3600956  2014         BRONX ACADEMY OF PROMISE CHARTER SCHOOL
9637   3900083  2014  Dayton Leadership Academies-Dayton View Campus

      Number of 4th Grade Reading Tests  \
8537                               70.0
9637                               28.0

      4th Grade Reading Proficiency Percentage-low  \
8537                                          20.0
9637                                          21.0

      4th Grade Reading Proficiency Percentage-high  \
8537                                           24.0
9637                                           39.0

      4th Grade Reading Proficiency Percentage-mid  \
8537                                          22.0
9637                                          30.0

      Number of 4th Grade Math Tests  \
8537                             NaN
9637                             NaN

      4th Grade Math Proficiency Percentage-low  \
8537                                        NaN
9637                                        NaN

      4th Grade Math Proficiency Percentage-high  \
8537                                         NaN
9637                                         NaN

      4th Grade Math Proficiency Percentage-mid  \
8537                                        NaN
9637                                        NaN

      Number of 8th Grade Reading Tests  \
8537                               50.0
9637                               42.0

      8th Grade Reading Proficiency Percentage-low  \
8537                                          30.0
9637                                          60.0

      8th Grade Reading Proficiency Percentage-high  \
8537                                           39.0
9637                                           69.0

      8th Grade Reading Proficiency Percentage-mid
8537                                          34.5
9637                                          64.5

The only two rows with missing values are for districts without information for 4th grade math scores.  As this project is focused on reading, we will keep these rows, ignoring their missing math scores.  In fact, this helps us recognize that we could drop information on math scores for the entire dataset.  This will simplify our dataset as well as take care of these missing values.

### 3.3.6 Keep only columns we may use

In [47]:
for col in scores.columns:
    print(col)

ID Number
year
District Name
Number of 4th Grade Reading Tests
4th Grade Reading Proficiency Percentage-low
4th Grade Reading Proficiency Percentage-high
4th Grade Reading Proficiency Percentage-mid
Number of 4th Grade Math Tests
4th Grade Math Proficiency Percentage-low
4th Grade Math Proficiency Percentage-high
4th Grade Math Proficiency Percentage-mid
Number of 8th Grade Reading Tests
8th Grade Reading Proficiency Percentage-low
8th Grade Reading Proficiency Percentage-high
8th Grade Reading Proficiency Percentage-mid

In [48]:
scores.drop(['Number of 4th Grade Math Tests', '4th Grade Math Proficiency Percentage-low', '4th Grade Math Proficiency Percentage-high', '4th Grade Math Proficiency Percentage-mid'], axis=1, inplace=True)
print(scores)

     ID Number  year                    District Name  \
0      0100005  2014                 Albertville City
1      0100006  2014                  Marshall County
2      0100007  2014                      Hoover City
3      0100008  2014                     Madison City
4      0100011  2014                       Leeds City
...        ...   ...                              ...
9995   3904565  2014      Wellington Exempted Village
9996   3904566  2014         Windham Exempted Village
9997   3904567  2014  Yellow Springs Exempted Village
9998   3904575  2014                 Allen East Local
9999   3904576  2014                       Bath Local

      Number of 4th Grade Reading Tests  \
0                                 389.0
1                                 440.0
2                                1011.0
3                                 734.0
4                                 145.0
...                                 ...
9995                               71.0
9996                               40.0
9997                               60.0
9998                               87.0
9999                              151.0

      4th Grade Reading Proficiency Percentage-low  \
0                                             31.0
1                                             29.0
2                                             56.0
3                                             70.0
4                                             20.0
...                                            ...
9995                                          85.0
9996                                          60.0
9997                                          90.0
9998                                          70.0
9999                                          65.0

      4th Grade Reading Proficiency Percentage-high  \
0                                              31.0
1                                              29.0
2                                              56.0
3                                              70.0
4                                              24.0
...                                             ...
9995                                           89.0
9996                                           69.0
9997                                          100.0
9998                                           74.0
9999                                           69.0

      4th Grade Reading Proficiency Percentage-mid  \
0                                             31.0
1                                             29.0
2                                             56.0
3                                             70.0
4                                             22.0
...                                            ...
9995                                          87.0
9996                                          64.5
9997                                          95.0
9998                                          72.0
9999                                          67.0

      Number of 8th Grade Reading Tests  \
0                                 334.0
1                                 393.0
2                                1138.0
3                                 778.0
4                                 118.0
...                                 ...
9995                               70.0
9996                               49.0
9997                               71.0
9998                               94.0
9999                              145.0

      8th Grade Reading Proficiency Percentage-low  \
0                                             36.0
1                                             42.0
2                                             67.0
3                                             67.0
4                                             50.0
...                                            ...
9995                                          70.0
9996                                          50.0
9997                                          80.0
9998                                          60.0
9999                                          70.0

      8th Grade Reading Proficiency Percentage-high  \
0                                              36.0
1                                              42.0
2                                              67.0
3                                              67.0
4                                              54.0
...                                             ...
9995                                           74.0
9996                                           59.0
9997                                           84.0
9998                                           64.0
9999                                           74.0

      8th Grade Reading Proficiency Percentage-mid
0                                             36.0
1                                             42.0
2                                             67.0
3                                             67.0
4                                             52.0
...                                            ...
9995                                          72.0
9996                                          54.5
9997                                          82.0
9998                                          62.0
9999                                          72.0

[8722 rows x 11 columns]

In [49]:
for col in scores.columns:
    print(col)

ID Number
year
District Name
Number of 4th Grade Reading Tests
4th Grade Reading Proficiency Percentage-low
4th Grade Reading Proficiency Percentage-high
4th Grade Reading Proficiency Percentage-mid
Number of 8th Grade Reading Tests
8th Grade Reading Proficiency Percentage-low
8th Grade Reading Proficiency Percentage-high
8th Grade Reading Proficiency Percentage-mid

# Part 4:  Double-check resulting (cleaned) datasets

In [50]:
bans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1586 entries, 0 to 793
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State                1586 non-null   object
 1   District             1586 non-null   object
 2   Origin of Challenge  1586 non-null   object
 3   Type of Ban          1586 non-null   object
 4   Author               1586 non-null   object
 5   Title                1586 non-null   object
 6   Frequency            1586 non-null   int64
 7   Date                 1586 non-null   object
dtypes: int64(1), object(7)
memory usage: 111.5+ KB

In [51]:
bans.head(30)

,State,District,Origin of Challenge,Type of Ban,Author,Title,Frequency,Date
0,Alaska,Anchorage School District,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
817,Pennsylvania,Wissahickon,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
1545,Texas,Spring Branch ISD,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
1535,Texas,Prosper ISD,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
303,New York,Yorktown Central School District,Formal Challenge,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2022-01-01
299,New York,Wappingers Central School District,Formal Challenge,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2022-03-01
805,Pennsylvania,Downington Area School District,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
810,Pennsylvania,Kutztown Area School District,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
263,Kansas,Goddard Public Schools,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
813,Pennsylvania,North Penn School District,Administrator,Banned from Libraries,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-09-01
1042,Texas,Keller,Formal Challenge,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
1551,Utah,Canyons School District,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
819,South Carolina,Fort Mill,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
244,Iowa,Waukee,Administrator,Banned from Libraries,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
241,Iowa,Ankeny Community School District,Formal Challenge,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
842,Texas,Birdville,Formal Challenge,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
220,Illinois,Lake Forest Schools,Administrator,Banned from Libraries,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
219,Illinois,Community High School District 117,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-12-01
188,Florida,Orange County,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
189,Florida,Pinellas County Schools,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
317,Ohio,Hudson,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-09-01
807,Pennsylvania,East Stroudsburg Area School District,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
851,Texas,Canutillo Independent School District,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
1572,Virginia,Virginia Beach,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-10-01
1562,Virginia,Harrisonburg,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
1561,Virginia,Fairfax County Public Schools,Formal Challenge,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-09-01
14,Florida,Brevard County Public Schools,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-01
1565,Virginia,Loudoun County Public School,Administrator,Banned from Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-09-01
1576,Washington,Central Kitsap,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2021-11-07
1580,Washington,Walla Walla School District,Formal Challenge,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,30,2022-02-01

In [52]:
bans.tail(30)

,State,District,Origin of Challenge,Type of Ban,Author,Title,Frequency,Date
539,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hong, Jess",Lovely,1,2021-09-01
540,Pennsylvania,Central York,Administrator,Banned from Classrooms,"hooks, bell",Teaching to Transgress: Education as the Pract...,1,2021-09-01
541,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hopkinson, Deborah",Michelle,1,2021-09-01
152,Florida,Indian River County School,Administrator,Banned Pending Investigation,"Rodowsky, Colby",Lucy Peale,1,2021-11-01
936,Texas,Granbury Independent School District,Administrator,Banned from Libraries and Classrooms,"Glines, Abbi",The Vincent Brothers (The Vincent Boys Series),1,2022-01-01
937,Texas,Granbury Independent School District,Administrator,Banned Pending Investigation,"Glines, Abbi",Under the Lights (The Field Party Series),1,2022-01-01
938,Texas,Granbury Independent School District,Administrator,Banned from Libraries and Classrooms,"Glines, Abbi",Until Friday Night (The Field Party Series),1,2022-01-01
939,Texas,Granbury Independent School District,Administrator,Banned from Libraries and Classrooms,"Glines, Abbi",Until the End (Sea Breeze Series),1,2022-01-01
940,Texas,Granbury Independent School District,Administrator,Banned Pending Investigation,"Gold, Susan Dudley",Roe v. Wade: A Woman's Choice?,1,2022-01-01
155,Florida,Indian River County School,Administrator,Banned from Libraries and Classrooms,"Sanchez, Alex",Bait,1,2021-11-01
942,Texas,Granbury Independent School District,Administrator,Banned Pending Investigation,"Greenman, Catherine",Hooked,1,2022-01-01
557,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jules, Jacqueline",Every Day Is Exciting (Sofía Martínez Series),1,2021-09-01
556,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jules, Jacqueline",Abuela's Special Letters (Sofía Martínez Series),1,2021-09-01
555,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jules, Jacqueline",Abuela's Birthday (Sofía Martínez Series),1,2021-09-01
554,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Johnson, Varian",What Were the Negro Leagues? (What was...? Ser...,1,2021-09-01
553,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Johnson, Varian",The Parker Inheritance,1,2021-09-01
948,Texas,Granbury Independent School District,Administrator,Banned Pending Investigation,"Homes, A. M.",Jack,1,2022-01-01
311,North Carolina,Pitt County Schools,Administrator,Banned from Classrooms,"Draper, Sharon M.",Forged By Fire,1,2021-11-07
551,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Johnshon, Chelsea,",IntersectionAllies: We Make Room for All,1,2021-09-01
550,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jiang, Ji-li","Red Kite, Blue Kite",1,2021-09-01
548,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jamieson, Victoria",When Stars Are Scattered,1,2021-09-01
547,Pennsylvania,Central York,Administrator,Banned from Classrooms,"James, LeBron",I Promise,1,2021-09-01
546,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Jacobs, Donald Trent",Teaching Truly: A Curriculum to Indigenize Mai...,1,2021-09-01
545,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hudson, Cheryl Willis",My Friend Maya Loves to Dance,1,2021-09-01
329,Oklahoma,Bristow Public Schools,Administrator,Banned from Libraries,"Golding, William",Lord of the Flies,1,2021-10-01
958,Texas,Granbury Independent School District,Administrator,Banned Pending Investigation,"Johnson, Kathleen Jeffrie",Target,1,2022-01-01
544,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hubbard, Crystal",Catching the Moon: The Story of a Young Girl's...,1,2021-09-01
543,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hort, Lenny",How Many Stars in the Sky?,1,2021-09-01
542,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Hopkinson, Deborah",What Is the Women's Rights Movement? (What was...,1,2021-09-01
793,Pennsylvania,Central York,Administrator,Banned from Classrooms,"Worthington, Michelle",Noah Chases the Wind,1,2021-09-01

In [53]:
bans.describe(include = 'all')

,State,District,Origin of Challenge,Type of Ban,Author,Title,Frequency,Date
count,1586,1586,1586,1586,1586,1586,1586.000000,1586
unique,26,86,2,4,797,1145,NaN,13
top,Texas,Central York,Administrator,Banned Pending Investigation,"Kobabe, Maia",Gender Queer: A Memoir,NaN,2021-09-01
freq,713,441,1517,731,30,30,NaN,456
mean,NaN,NaN,NaN,NaN,NaN,NaN,3.056747,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,5.115751,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN

In [54]:
State_Info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1586 entries, 1277 to 818
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   State                      1586 non-null   object
 1   District                   1586 non-null   object
 2   Date of Challenge/Removal  1586 non-null   object
 3   State_Frequency            1586 non-null   int64
 4   District_Frequency         1586 non-null   int64
dtypes: int64(2), object(3)
memory usage: 74.3+ KB

In [55]:
Most_Controversial.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 39
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Title                      364 non-null    object
 1   Author                     364 non-null    object
 2   Date of Challenge/Removal  364 non-null    object
 3   Frequency                  364 non-null    int64
dtypes: int64(1), object(3)
memory usage: 14.2+ KB

In [56]:
district.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1580 entries, 1545 to 276
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   State                      1580 non-null   object
 1   District                   1580 non-null   object
 2   Date of Challenge/Removal  1580 non-null   object
dtypes: object(3)
memory usage: 49.4+ KB

In [57]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8722 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   ID Number                                      8722 non-null   object
 1   year                                           8722 non-null   int64
 2   District Name                                  8722 non-null   object
 3   Number of 4th Grade Reading Tests              8722 non-null   float64
 4   4th Grade Reading Proficiency Percentage-low   8722 non-null   float64
 5   4th Grade Reading Proficiency Percentage-high  8722 non-null   float64
 6   4th Grade Reading Proficiency Percentage-mid   8722 non-null   float64
 7   Number of 8th Grade Reading Tests              8722 non-null   float64
 8   8th Grade Reading Proficiency Percentage-low   8722 non-null   float64
 9   8th Grade Reading Proficiency Percentage-high  8722 non-null   float64
 10  8th Grade Reading Proficiency Percentage-mid   8722 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 817.7+ KB

In [58]:
scores.head(30)

,ID Number,year,District Name,Number of 4th Grade Reading Tests,4th Grade Reading Proficiency Percentage-low,4th Grade Reading Proficiency Percentage-high,4th Grade Reading Proficiency Percentage-mid,Number of 8th Grade Reading Tests,8th Grade Reading Proficiency Percentage-low,8th Grade Reading Proficiency Percentage-high,8th Grade Reading Proficiency Percentage-mid
0,0100005,2014,Albertville City,389.0,31.0,31.0,31.0,334.0,36.0,36.0,36.0
1,0100006,2014,Marshall County,440.0,29.0,29.0,29.0,393.0,42.0,42.0,42.0
2,0100007,2014,Hoover City,1011.0,56.0,56.0,56.0,1138.0,67.0,67.0,67.0
3,0100008,2014,Madison City,734.0,70.0,70.0,70.0,778.0,67.0,67.0,67.0
4,0100011,2014,Leeds City,145.0,20.0,24.0,22.0,118.0,50.0,54.0,52.0
5,0100012,2014,Boaz City,194.0,35.0,39.0,37.0,173.0,40.0,44.0,42.0
6,0100013,2014,Trussville City,332.0,58.0,58.0,58.0,345.0,55.0,55.0,55.0
7,0100030,2014,Alexander City,215.0,30.0,34.0,32.0,236.0,45.0,49.0,47.0
8,0100060,2014,Andalusia City,121.0,20.0,24.0,22.0,124.0,50.0,54.0,52.0
9,0100090,2014,Anniston City,156.0,15.0,19.0,17.0,136.0,30.0,34.0,32.0
10,0100100,2014,Arab City,189.0,55.0,59.0,57.0,186.0,70.0,74.0,72.0
11,0100120,2014,Athens City,254.0,50.0,54.0,52.0,270.0,45.0,49.0,47.0
12,0100180,2014,Attalla City,80.0,45.0,49.0,47.0,173.0,30.0,34.0,32.0
13,0100185,2014,Saraland City,208.0,50.0,54.0,52.0,222.0,50.0,54.0,52.0
14,0100188,2014,Chickasaw City,63.0,15.0,19.0,17.0,78.0,30.0,34.0,32.0
15,0100189,2014,Satsuma City,99.0,40.0,44.0,42.0,98.0,50.0,54.0,52.0
16,0100190,2014,Alabaster City,466.0,33.0,33.0,33.0,478.0,50.0,50.0,50.0
17,0100194,2014,Pelham City,256.0,50.0,54.0,52.0,283.0,50.0,54.0,52.0
18,0100210,2014,Auburn City,643.0,56.0,56.0,56.0,626.0,64.0,64.0,64.0
19,0100240,2014,Autauga County,728.0,36.0,36.0,36.0,788.0,58.0,58.0,58.0
20,0100270,2014,Baldwin County,2341.0,36.0,36.0,36.0,2349.0,45.0,45.0,45.0
21,0100300,2014,Barbour County,66.0,10.0,14.0,12.0,82.0,20.0,24.0,22.0
22,0100330,2014,Bessemer City,304.0,12.0,12.0,12.0,277.0,15.0,19.0,17.0
23,0100360,2014,Bibb County,233.0,30.0,34.0,32.0,261.0,35.0,39.0,37.0
24,0100390,2014,Birmingham City,1877.0,15.0,15.0,15.0,1683.0,30.0,30.0,30.0
25,0100420,2014,Blount County,614.0,42.0,42.0,42.0,669.0,34.0,34.0,34.0
26,0100450,2014,Brewton City,89.0,50.0,54.0,52.0,80.0,50.0,54.0,52.0
27,0100480,2014,Bullock County,104.0,15.0,19.0,17.0,98.0,20.0,24.0,22.0
28,0100510,2014,Butler County,222.0,20.0,24.0,22.0,220.0,30.0,34.0,32.0
29,0100540,2014,Calhoun County,671.0,36.0,36.0,36.0,780.0,45.0,45.0,45.0

In [59]:
scores.tail(30)

,ID Number,year,District Name,Number of 4th Grade Reading Tests,4th Grade Reading Proficiency Percentage-low,4th Grade Reading Proficiency Percentage-high,4th Grade Reading Proficiency Percentage-mid,Number of 8th Grade Reading Tests,8th Grade Reading Proficiency Percentage-low,8th Grade Reading Proficiency Percentage-high,8th Grade Reading Proficiency Percentage-mid
9970,3904537,2014,Georgetown Exempted Village,73.0,50.0,54.0,52.0,96.0,70.0,74.0,72.0
9971,3904538,2014,Gibsonburg Exempted Village,83.0,65.0,69.0,67.0,74.0,40.0,44.0,42.0
9972,3904539,2014,Granville Exempted Village,172.0,80.0,84.0,82.0,186.0,90.0,94.0,92.0
9973,3904540,2014,Greenfield Exempted Village,149.0,55.0,59.0,57.0,136.0,70.0,74.0,72.0
9974,3904541,2014,Hicksville Exempted Village,65.0,75.0,79.0,77.0,68.0,75.0,79.0,77.0
9975,3904542,2014,Hubbard Exempted Village,166.0,80.0,84.0,82.0,157.0,70.0,74.0,72.0
9976,3904543,2014,Indian Hill Exempted Village,136.0,90.0,94.0,92.0,178.0,90.0,94.0,92.0
9977,3904545,2014,Lisbon Exempted Village,44.0,80.0,89.0,84.5,72.0,75.0,79.0,77.0
9978,3904546,2014,Loudonville-Perrysville Exempted Village,81.0,85.0,89.0,87.0,97.0,50.0,54.0,52.0
9979,3904547,2014,Marysville Exempted Village,418.0,82.0,82.0,82.0,435.0,74.0,74.0,74.0
9980,3904548,2014,Mechanicsburg Exempted Village,71.0,60.0,64.0,62.0,65.0,70.0,74.0,72.0
9981,3904549,2014,Mentor Exempted Village,552.0,76.0,76.0,76.0,555.0,79.0,79.0,79.0
9982,3904550,2014,Milford Exempted Village,492.0,83.0,83.0,83.0,485.0,90.0,90.0,90.0
9983,3904551,2014,Milton-Union Exempted Village,123.0,85.0,89.0,87.0,117.0,80.0,84.0,82.0
9984,3904552,2014,Montpelier Exempted Village,67.0,75.0,79.0,77.0,88.0,70.0,74.0,72.0
9985,3904553,2014,Mount Gilead Exempted Village,95.0,65.0,69.0,67.0,104.0,75.0,79.0,77.0
9986,3904554,2014,Newcomerstown Exempted Village,68.0,65.0,69.0,67.0,75.0,65.0,69.0,67.0
9987,3904555,2014,New Richmond Exempted Village,146.0,75.0,79.0,77.0,178.0,75.0,79.0,77.0
9988,3904556,2014,Newton Falls Exempted Village,75.0,70.0,74.0,72.0,103.0,50.0,54.0,52.0
9989,3904557,2014,Paulding Exempted Village,100.0,70.0,74.0,72.0,112.0,60.0,64.0,62.0
9990,3904558,2014,Perrysburg Exempted Village,384.0,85.0,85.0,85.0,365.0,83.0,83.0,83.0
9991,3904560,2014,Rossford Exempted Village,119.0,65.0,69.0,67.0,103.0,65.0,69.0,67.0
9992,3904561,2014,Tipp City Exempted Village,195.0,85.0,89.0,87.0,188.0,85.0,89.0,87.0
9993,3904563,2014,Versailles Exempted Village,90.0,80.0,84.0,82.0,113.0,90.0,94.0,92.0
9994,3904564,2014,Wauseon Exempted Village,125.0,70.0,74.0,72.0,156.0,70.0,74.0,72.0
9995,3904565,2014,Wellington Exempted Village,71.0,85.0,89.0,87.0,70.0,70.0,74.0,72.0
9996,3904566,2014,Windham Exempted Village,40.0,60.0,69.0,64.5,49.0,50.0,59.0,54.5
9997,3904567,2014,Yellow Springs Exempted Village,60.0,90.0,100.0,95.0,71.0,80.0,84.0,82.0
9998,3904575,2014,Allen East Local,87.0,70.0,74.0,72.0,94.0,60.0,64.0,62.0
9999,3904576,2014,Bath Local,151.0,65.0,69.0,67.0,145.0,70.0,74.0,72.0

In [60]:
scores.describe()

,year,Number of 4th Grade Reading Tests,4th Grade Reading Proficiency Percentage-low,4th Grade Reading Proficiency Percentage-high,4th Grade Reading Proficiency Percentage-mid,Number of 8th Grade Reading Tests,8th Grade Reading Proficiency Percentage-low,8th Grade Reading Proficiency Percentage-high,8th Grade Reading Proficiency Percentage-mid
count,8722.0,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000
mean,2014.0,272.474203,43.139876,52.767026,47.953451,268.374111,43.637812,53.440954,48.539383
std,0.0,933.195926,22.488712,22.123313,21.369721,877.893997,22.555426,22.132390,21.368377
min,2014.0,6.000000,0.000000,3.000000,2.500000,6.000000,0.000000,5.000000,2.500000
25%,2014.0,37.000000,25.250000,39.000000,30.000000,36.000000,30.000000,39.000000,30.000000
50%,2014.0,84.000000,44.000000,49.000000,47.000000,86.000000,45.000000,49.000000,47.000000
75%,2014.0,217.000000,60.000000,69.000000,67.000000,224.000000,60.000000,69.000000,67.000000
max,2014.0,42520.000000,97.000000,100.000000,97.500000,36269.000000,99.000000,100.000000,99.500000

# Part 5:  Save cleaned datasets

In [61]:
scores.to_csv(r'banned-scores.csv')

In [62]:
bans.to_csv(r'banned-bans.csv')

In [63]:
State_Info.to_csv(r'banned-state.csv')

In [64]:
Most_Controversial.to_csv(r'banned-most.csv')

In [65]:
district.to_csv(r'banned-district.csv')